// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Record 一台主机已确认的发行版（用于侧栏/概览图标，操作系统几乎不变）
 */
export interface Record {
    "host": string;
    "osRelease": string;
    "updatedAt": number;
}
