// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Addr 端点的一个 IPv4 地址
 */
export interface Addr {
    "ip": string;

    /**
     * 0 表示网段未知（来自 HostName / 出口 IP）
     */
    "prefix": number;
    "iface"?: string;
    "kind": string;
    "source": string;
}

/**
 * Candidate 一条候选路径：客户端连接服务端（Server 侧）的 Target 地址
 */
export interface Candidate {
    /**
     * lan / wan
     */
    "kind": string;

    /**
     * same / routed / overlay / public / nat
     */
    "relation": string;

    /**
     * 服务端在哪一侧：a / b
     */
    "server": string;
    "target": Addr;

    /**
     * 同网段时客户端侧的对应地址
     */
    "clientAddr"?: Addr | null;

    /**
     * 探测时服务端监听的端口
     */
    "port"?: number;
    "probed": boolean;
    "ok": boolean;
    "rttMs": number;
    "reason"?: string;
}

/**
 * EndpointView 一侧端点的地址视图
 */
export interface EndpointView {
    "id": string;
    "label": string;
    "local": boolean;
    "addrs": Addr[] | null;

    /**
     * 展示用：网段或单地址
     */
    "segments": string[] | null;
    "error"?: string;
}

/**
 * GroupRequest 分组测速请求
 */
export interface GroupRequest {
    /**
     * 分组名（展示与历史用）
     */
    "group": string;
    "hosts": string[] | null;

    /**
     * star / mesh
     */
    "mode": string;

    /**
     * 星型中心机
     */
    "center": string;
    "params": Params;
}

/**
 * HistoryItem 列表行（不带采样序列）
 */
export interface HistoryItem {
    "id": string;
    "kind": string;
    "createdAt": number;
    "status": string;
    "error"?: string;
    "params": Params;
    "a"?: string;
    "b"?: string;
    "path"?: Candidate | null;
    "summary"?: Summary | null;
    "group"?: string;
    "center"?: string;
    "pairCount": number;
    "pairOk": number;

    /**
     * 分组：成功轮次的平均吞吐
     */
    "avgAB": number;
}

/**
 * PairResult 分组测速中的一轮
 */
export interface PairResult {
    "a": string;
    "b": string;

    /**
     * pending / running / done / failed / nolan / stopped
     */
    "status": string;
    "reason"?: string;
    "path"?: Candidate | null;
    "summary"?: Summary | null;
    "samples"?: Sample[] | null;
}

/**
 * Params 测速参数
 */
export interface Params {
    /**
     * tcp / udp
     */
    "protocol": string;

    /**
     * -P 1–64
     */
    "parallel": number;

    /**
     * -t 3–300 秒
     */
    "duration": number;

    /**
     * forward / reverse / bidir
     */
    "direction": string;

    /**
     * UDP 总目标带宽，0 表示不限
     */
    "udpBandwidthMbps": number;

    /**
     * 0 表示 5201–5210 自动
     */
    "port": number;

    /**
     * -O 忽略开头秒数
     */
    "omit": number;

    /**
     * -w，0 表示系统默认
     */
    "windowKB": number;

    /**
     * -M，0 表示系统默认
     */
    "mss": number;

    /**
     * -C，仅 Linux 客户端
     */
    "congestion": string;

    /**
     * -i 0.5 / 1
     */
    "interval": number;
}

/**
 * PathReport DetectPaths 的返回
 */
export interface PathReport {
    "a": EndpointView;
    "b": EndpointView;
    "port": number;
    "candidates": Candidate[] | null;
    "lan": PathSummary;
    "wan": PathSummary;
    "decision": string;
    "message": string;
}

/**
 * PathSummary 一类路径（局域网或广域网）的汇总，对应前端一张卡片
 */
export interface PathSummary {
    "available": boolean;
    "best"?: Candidate | null;
    "reason"?: string;
}

/**
 * Record 一条历史记录
 */
export interface Record {
    "id": string;
    "kind": string;
    "createdAt": number;

    /**
     * done / failed / stopped
     */
    "status": string;
    "error"?: string;
    "params": Params;
    "a"?: string;
    "b"?: string;
    "aId"?: string;
    "bId"?: string;
    "path"?: Candidate | null;
    "summary"?: Summary | null;
    "samples"?: Sample[] | null;
    "group"?: string;
    "hosts"?: string[] | null;
    "center"?: string;
    "pairs"?: PairResult[] | null;
}

/**
 * Sample 一个采样点；吞吐单位 bit/s，方向相对 A、B
 */
export interface Sample {
    "t": number;
    "ab": number;
    "ba": number;
    "retransmits": number;
    "rttMs": number;
    "jitterMs": number;
    "lostPct": number;
    "omitted": boolean;
    "streamsAB"?: number[] | null;
    "streamsBA"?: number[] | null;
}

/**
 * StartRequest 两机测速请求；Server / Target 来自 DetectPaths 选中的候选
 */
export interface StartRequest {
    "a": string;
    "b": string;
    "path": Candidate;
    "params": Params;
}

/**
 * Summary 一次测速的汇总
 */
export interface Summary {
    /**
     * 平均吞吐（接收端统计），未测该方向为 0
     */
    "ab": number;
    "ba": number;
    "peakAB": number;
    "peakBA": number;
    "retransmits": number;
    "rttMs": number;
    "jitterMs": number;
    "lostPct": number;
    "seconds": number;
    "cpuClient": number;
    "cpuServer": number;
}
