// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Cursor 某台主机已经处理过的扫描日，以及仍在催的域名。
 * PartialDate 有值表示这一天还有频道没送完，AppliedDate 先不动。
 */
export interface Cursor {
    "appliedDate": string;
    "nagging": string[] | null;
    "partialDate": string;
    "sent": Sent[] | null;
}

/**
 * Notice 一条待发通知。Title 和 Body 三路频道原样使用。
 */
export interface Notice {
    "domainKey": string;
    "title": string;
    "body": string;
    "expired": boolean;
}

/**
 * Result 一次扫描相对「上次还在催的域名」的差额。
 */
export interface Result {
    "nags": Notice[] | null;
    "recoveries": Notice[] | null;
    "nextNagging": string[] | null;
}

/**
 * Sent 某一天里某个通知已经送到的频道。没送成的下一次轮询只补那一路。
 */
export interface Sent {
    "key": string;
    "desktop": boolean;
    "wecom": boolean;
}
