// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppNode 按身份归并后的应用节点（可含多进程）。
 */
export interface AppNode {
    "key": string;
    "name": string;

    /**
     * 语言：java / go / javascript / python / csharp / swift / …
     */
    "runtime": string;

    /**
     * runtime / service
     */
    "kind": string;

    /**
     * high / medium
     */
    "confidence": string;
    "evidence": string[] | null;
    "procCount": number;
    "threadCount": number;
    "cpu": number;
    "rss": number;

    /**
     * bytes/s；无数据时为 0，前端用 RateKnown 判断
     */
    "diskReadRate": number;

    /**
     * bytes/s
     */
    "diskWriteRate": number;

    /**
     * bytes/s
     */
    "netInRate": number;

    /**
     * bytes/s
     */
    "netOutRate": number;

    /**
     * 是否已有速率采样
     */
    "rateKnown": boolean;
    "procs": ProcNode[] | null;
}

/**
 * ProcNode 单个运行时进程。
 */
export interface ProcNode {
    "pid": number;
    "ppid": number;
    "user": string;
    "kind": string;
    "confidence": string;
    "evidence": string[] | null;
    "cpu": number;
    "rss": number;
    "threadCount": number;
    "elapsed": number;
    "exe": string;
    "cwd": string;
    "cmd": string;
    "args": string[] | null;
    "ports": number[] | null;
    "listenAddresses": string[] | null;
    "diskRead": number;
    "diskWrite": number;
    "netIn": number;
    "netOut": number;
    "diskReadRate": number;
    "diskWriteRate": number;
    "netInRate": number;
    "netOutRate": number;
    "rateKnown": boolean;

    /**
     * java: jar/mainClass/xmx；go: module/goVersion；node: script；self: "1"
     */
    "extra": { [_ in string]?: string } | null;
    "threads": ThreadNode[] | null;
}

/**
 * ProcResource 单个进程打开的文件、目录、socket 或 pipe。
 */
export interface ProcResource {
    "fd": string;
    "type": string;
    "name": string;
    "access": string;
    "protocol": string;
    "state": string;
    "localAddress": string;
    "remoteAddress": string;
}

/**
 * ResourceSnapshot 单个进程按需读取的文件描述符快照。
 */
export interface ResourceSnapshot {
    "pid": number;
    "resources": ProcResource[] | null;
    "warnings": string[] | null;
}

/**
 * Snapshot 一次本机应用扫描结果。
 */
export interface Snapshot {
    "sampledAt": number;
    "apps": AppNode[] | null;
    "warnings": string[] | null;
}

/**
 * ThreadNode 进程内线程摘要。
 */
export interface ThreadNode {
    "tid": number;
    "name": string;
    "cpu": number;
    "state": string;
}
