// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Agent agent 状态与历史数据服务（数据全部来自目标主机上的 spanel-agent）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentcli$0 from "./internal/agentcli/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentinstall$0 from "./internal/agentinstall/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AgentBatchInstall 批量安装/更新（幂等，逐台并发 3；单台失败不影响其余）。
 * hosts 为空时自动覆盖 ssh config 里的全部主机。
 */
export function AgentBatchInstall(hosts: string[] | null): $CancellablePromise<$models.AgentBatchResult[] | null> {
    return $Call.ByID(2316575603, hosts);
}

/**
 * AgentCurrent 最新采样 + 静态信息（概览页轮询；比 /collect 零命令更快）
 */
export function AgentCurrent(host: string): $CancellablePromise<agentcli$0.CurrentResponse> {
    return $Call.ByID(4106612253, host);
}

/**
 * AgentEmbedded 面板是否已内置该架构的 agent 二进制
 */
export function AgentEmbedded(arch: string): $CancellablePromise<boolean> {
    return $Call.ByID(1368222066, arch);
}

/**
 * AgentEvents agent 事件列表（默认最近 24h）
 */
export function AgentEvents(host: string): $CancellablePromise<agentcli$0.AgentEvent[] | null> {
    return $Call.ByID(534794697, host);
}

/**
 * AgentHealth agent 健康/自身资源（含版本、RSS、丢弃计数）
 */
export function AgentHealth(host: string): $CancellablePromise<agentcli$0.Health> {
    return $Call.ByID(3718230254, host);
}

/**
 * AgentLatestVersion 面板内置的 agent 版本（前端比对显示「可更新」）
 */
export function AgentLatestVersion(): $CancellablePromise<string> {
    return $Call.ByID(2752371469);
}

/**
 * AgentProbeInfo 探测目标主机（架构/systemd/安装状态）
 */
export function AgentProbeInfo(host: string): $CancellablePromise<agentinstall$0.ProbeInfo> {
    return $Call.ByID(3765657754, host);
}

/**
 * AgentRange 历史时间序列（from/to 为 Unix 秒；src: auto/raw/agg）
 */
export function AgentRange(host: string, $from: number, to: number, src: string): $CancellablePromise<agentcli$0.RangeResponse> {
    return $Call.ByID(2920167021, host, $from, to, src);
}

/**
 * AgentStatus 探测主机 agent 状态（30s 缓存；force 跳过缓存）
 */
export function AgentStatus(host: string, force: boolean): $CancellablePromise<agentcli$0.Status> {
    return $Call.ByID(436990650, host, force);
}

/**
 * AgentSummary 最近 1h/6h/24h/7d 摘要
 */
export function AgentSummary(host: string): $CancellablePromise<agentcli$0.SummaryRange[] | null> {
    return $Call.ByID(2670964336, host);
}

/**
 * InstallAgent 安装或更新单台（幂等）：探测 → 上传校验 → 原子替换 → systemd 启动
 * → 隧道健康检查（版本比对）→ 失败自动回滚旧版。
 */
export function InstallAgent(host: string): $CancellablePromise<void> {
    return $Call.ByID(2696334783, host);
}

/**
 * UninstallAgent 卸载 agent；keepData=true 保留数据目录（重装可续看历史）
 */
export function UninstallAgent(host: string, keepData: boolean): $CancellablePromise<void> {
    return $Call.ByID(3883522796, host, keepData);
}
