// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlertHistory 应用内告警历史服务（本地落盘）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as alerthistory$0 from "./internal/alerthistory/models.js";

/**
 * Append 追加一条告警历史，返回带 id / at 的完整事件。
 */
export function Append(event: alerthistory$0.Event): $CancellablePromise<alerthistory$0.Event> {
    return $Call.ByID(4009815974, event);
}

/**
 * Clear 清空全部告警历史。
 */
export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(570922475);
}

/**
 * Delete 删除指定事件，返回实际删除条数。
 */
export function Delete(ids: string[] | null): $CancellablePromise<number> {
    return $Call.ByID(3905395677, ids);
}

/**
 * List 返回最近 limit 条（新→旧）；limit≤0 表示全部。
 */
export function List(limit: number): $CancellablePromise<alerthistory$0.Event[] | null> {
    return $Call.ByID(4148414366, limit);
}

/**
 * ListByHost 返回指定主机最近 limit 条；limit≤0 表示该主机全部。
 */
export function ListByHost(host: string, limit: number): $CancellablePromise<alerthistory$0.Event[] | null> {
    return $Call.ByID(2616732097, host, limit);
}

/**
 * MarkAllRead 全部已读；host 非空则只标该主机。
 */
export function MarkAllRead(host: string): $CancellablePromise<void> {
    return $Call.ByID(790217014, host);
}

/**
 * MarkRead 将指定事件标为已读。
 */
export function MarkRead(id: string): $CancellablePromise<void> {
    return $Call.ByID(1525285967, id);
}

/**
 * UnreadCount 未读告警条数。
 */
export function UnreadCount(): $CancellablePromise<number> {
    return $Call.ByID(80145944);
}
