// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSession 应用启动 / 退出运行日志服务（本地落盘）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appsession$0 from "./internal/appsession/models.js";

/**
 * Clear 清空历史会话（保留当前会话）。
 */
export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(3507306808);
}

/**
 * Current 返回当前运行中的会话；未记录时返回零值。
 */
export function Current(): $CancellablePromise<appsession$0.Session> {
    return $Call.ByID(2263913528);
}

/**
 * List 返回最近 limit 条会话（新→旧）；limit≤0 表示全部。
 */
export function List(limit: number): $CancellablePromise<appsession$0.Session[] | null> {
    return $Call.ByID(1965976559, limit);
}
