// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppUpdate 应用内更新服务（前端绑定）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelUpdate 取消正在进行的下载。
 */
export function CancelUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3829431401);
}

/**
 * CheckUpdate 立即检查更新（设置页「检查更新」）。
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(277752387);
}

/**
 * GetUpdateState 返回当前更新状态。
 */
export function GetUpdateState(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(1982659664);
}

/**
 * RemindLater 24 小时内不再提醒当前版本（仅可选更新）。
 */
export function RemindLater(): $CancellablePromise<void> {
    return $Call.ByID(2328460723);
}

/**
 * SetAutoCheck 开关自动检查更新；强制更新不受影响。
 */
export function SetAutoCheck(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1795519639, on);
}

/**
 * SkipVersion 不再提醒该版本（仅可选更新）。
 */
export function SkipVersion(version: string): $CancellablePromise<void> {
    return $Call.ByID(2562667723, version);
}

/**
 * StartUpdate 开始下载并安装新版本，完成后自动重启。
 */
export function StartUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3431306587);
}
