// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Backup 主机配置备份服务：聚合 ssh config / 分组 / 主机图标为单个 JSON 文件，支持导出与恢复
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportBackup 导出主机配置到 dir 下的日期文件夹（如 dir/2026-08-20/serverpanel-backup.json）
 * 同名日期文件夹已存在时整体覆盖（同一天重复导出会覆盖当天旧备份）
 * 成功返回摘要文案
 */
export function ExportBackup(dir: string): $CancellablePromise<string> {
    return $Call.ByID(3036406954, dir);
}

/**
 * ImportBackup 从备份文件恢复主机配置
 *   - overwrite=false：已存在的主机跳过（保留本地配置）
 *   - overwrite=true：已存在的主机先删后写，字段以备份为准
 * 
 * 备份文件可能被手工编辑过：别名与字段值先校验再写入，避免写出畸形 Host 块。
 * Git 托管条目（github.com 等）即使在覆盖模式下也不动——导出时本就不含它们。
 * 分组：引用的主机若不存在则剔除；本地已有同名或同 ID 分组时合并进去
 * （保留本地名称与排序，只并入备份的主机引用），否则按备份新建。
 */
export function ImportBackup(path: string, overwrite: boolean): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByID(1782992497, path, overwrite);
}

/**
 * ReadBackup 读取并校验备份文件（导入预览用）
 */
export function ReadBackup(path: string): $CancellablePromise<$models.BackupData | null> {
    return $Call.ByID(515496528, path);
}
