// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Backup 跨平台主机配置迁移：主机（含密码）、分组、图标、私钥与 known_hosts
 * 打包为单个 .zip，在 macOS / Windows / Linux 之间导出与恢复。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportBackup 导出迁移包到 path（无 .zip 后缀时自动补上），返回摘要文案
 */
export function ExportBackup(path: string): $CancellablePromise<string> {
    return $Call.ByID(3036406954, path);
}

/**
 * PreviewBackup 读取迁移包并给出恢复预览（不修改本机任何数据）
 */
export function PreviewBackup(path: string): $CancellablePromise<$models.BackupPreview | null> {
    return $Call.ByID(2772364228, path);
}

/**
 * RestoreBackup 从迁移包恢复：
 *   - overwrite=false：本机已有的同名主机跳过
 *   - overwrite=true：同名主机以备份为准（备份无密码时保留本机密码）
 * 
 * 恢复前会先吸收本机 SSH 配置的外部修改并做本地快照；生成配置失败时回滚 Panel 数据。
 * 恢复不做连接测试，换机后部分主机暂时不可达不影响恢复。
 */
export function RestoreBackup(path: string, overwrite: boolean): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByID(3751494946, path, overwrite);
}
