// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Certs 证书服务：本地证书/私钥配对校验与上传
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckCertPair 本地校验证书与私钥是否配对
 * localPaths: 用户拖入的文件（任意顺序，自动识别哪个是证书、哪个是私钥；
 * 也支持单个文件里同时包含证书和私钥两个 PEM 块）
 * 只有两者公钥完全一致才返回结果，否则返回错误
 */
export function CheckCertPair(localPaths: string[] | null): $CancellablePromise<$models.CertPairCheck> {
    return $Call.ByID(1074098829, localPaths);
}

/**
 * UploadCertPair 把已校验配对的证书+私钥上传到远程 /etc/nginx/cert
 */
export function UploadCertPair(host: string, certPath: string, keyPath: string): $CancellablePromise<void> {
    return $Call.ByID(4044567890, host, certPath, keyPath);
}
