// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CertNotify 证书到期通知的差额计算与去重游标。检测在 spanel-agent，发送在面板。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentcli$0 from "./internal/agentcli/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as certnotify$0 from "./internal/certnotify/models.js";

/**
 * CommitCursor 记下该主机这次扫描日已经处理完。
 */
export function CommitCursor(host: string, c: certnotify$0.Cursor): $CancellablePromise<void> {
    return $Call.ByID(2682384538, host, c);
}

/**
 * GetCursor 读取该主机已处理的扫描日和仍在催的域名。
 */
export function GetCursor(host: string): $CancellablePromise<certnotify$0.Cursor> {
    return $Call.ByID(2906854417, host);
}

/**
 * Plan 按本次快照和上次还在催的域名，算出今天要发的催办与恢复。
 */
export function Plan(host: string, snap: agentcli$0.CertCheckSnapshot, nagging: string[] | null): $CancellablePromise<certnotify$0.Result> {
    return $Call.ByID(3506593934, host, snap, nagging);
}

/**
 * RenameCursor 主机改名时把去重游标带走。
 */
export function RenameCursor($from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(954493565, $from, to);
}
