// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Files 文件服务：上传（SFTP）+ 进度 + 可选编码规范化
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filetext$0 from "./internal/filetext/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckLocalPaths 检测本地路径（文件/文件夹混合），返回所有「非 Linux 标准」的文本文件清单
 * 二进制 / 标准 UTF-8+LF / 超大文件 均跳过（不需用户决策）
 */
export function CheckLocalPaths(localPaths: string[] | null): $CancellablePromise<$models.LocalTextCheck[] | null> {
    return $Call.ByID(1159685526, localPaths);
}

/**
 * NormalizeFileToLinux 将远程文本文件规范为 UTF-8（无 BOM）+ LF
 * 写前自动备份为 <file>.bak.YYYYMMDD-HHMMSS
 * 成功后返回新的预览结果（needsNormalize=false）
 */
export function NormalizeFileToLinux(host: string, file: string): $CancellablePromise<filetext$0.Preview> {
    return $Call.ByID(592903667, host, file);
}

/**
 * ReadFilePreview（Files 服务）读取远程文本文件：返回编码/换行检测 + UTF-8 内容
 * 比 ReadFileText 更完整，供预览抽屉状态栏与「转 Linux 标准」使用
 */
export function ReadFilePreview(host: string, file: string): $CancellablePromise<filetext$0.Preview> {
    return $Call.ByID(2484376929, host, file);
}

/**
 * UploadDir 递归上传本地文件夹到远程主机，保留目录结构
 * localDir: 本地文件夹绝对路径
 * remoteDir: 远程目标目录（绝对路径，会自动创建）
 * normalize: true 时对其中「非标准文本」文件转为 UTF-8(无BOM)+LF
 */
export function UploadDir(host: string, localDir: string, remoteDir: string, normalize: boolean): $CancellablePromise<string> {
    return $Call.ByID(453272367, host, localDir, remoteDir, normalize);
}

/**
 * UploadFile 上传本地单文件到远程主机指定目录
 * localPath: 本地文件绝对路径（由 Wails 文件拖拽提供）
 * remoteDir: 远程目标目录（绝对路径，会自动创建）
 * normalize: true 时若文件是「非标准文本」则转为 UTF-8(无BOM)+LF 后再上传
 * 返回上传后的完整远程路径
 */
export function UploadFile(host: string, localPath: string, remoteDir: string, normalize: boolean): $CancellablePromise<string> {
    return $Call.ByID(1545598286, host, localPath, remoteDir, normalize);
}

/**
 * UploadPaths 批量上传多个本地路径（文件/文件夹混合）到远程目录，用于拖拽上传。
 * convertPaths: 需要「转 UTF-8(无BOM)+LF」的本地文件绝对路径集合（来自编码检查弹窗勾选）；
 * 文件夹内的文件按其绝对路径是否命中 convertPaths 决定是否转换。
 */
export function UploadPaths(host: string, localPaths: string[] | null, convertPaths: string[] | null, remoteDir: string): $CancellablePromise<void> {
    return $Call.ByID(2239550740, host, localPaths, convertPaths, remoteDir);
}
