// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Files 文件服务：上传（SFTP）+ 进度 + 可选编码规范化
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filetext$0 from "./internal/filetext/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "./internal/monitor/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckLocalPaths 检测本地路径（文件/文件夹混合），返回所有「非 Linux 标准」的文本文件清单
 * 二进制 / 标准 UTF-8+LF / 超大文件 均跳过（不需用户决策）
 */
export function CheckLocalPaths(localPaths: string[] | null): $CancellablePromise<$models.LocalTextCheck[] | null> {
    return $Call.ByID(1159685526, localPaths);
}

/**
 * DeleteLocalPaths 删除本机文件或目录（递归）。拒绝删除主目录和盘符根下的系统目录本身。
 */
export function DeleteLocalPaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(963859463, paths);
}

/**
 * DeleteSftpPaths 用 SFTP 删除远程文件或目录（递归，不走 agent）。
 */
export function DeleteSftpPaths(host: string, paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1019214649, host, paths);
}

/**
 * DownloadSftp 把远程文件或目录下到本地目录，返回本地完整路径。
 * 目录按原名递归拷贝到 localDir 下。
 */
export function DownloadSftp(host: string, remotePath: string, localDir: string): $CancellablePromise<string> {
    return $Call.ByID(892953152, host, remotePath, localDir);
}

/**
 * DownloadSftpPaths 一次连接下载多个远程文件或目录到同一本机目录。
 */
export function DownloadSftpPaths(host: string, remotePaths: string[] | null, localDir: string): $CancellablePromise<void> {
    return $Call.ByID(2153427740, host, remotePaths, localDir);
}

/**
 * DownloadSftpPathsAs 按冲突策略下载。mode 为 overwrite 或 rename。
 */
export function DownloadSftpPathsAs(host: string, remotePaths: string[] | null, localDir: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(3228000380, host, remotePaths, localDir, mode);
}

/**
 * ListLocalDir 列本机目录，给 SFTP 左栏用。
 */
export function ListLocalDir(dir: string): $CancellablePromise<monitor$0.FileEntry[] | null> {
    return $Call.ByID(2114530487, dir);
}

/**
 * ListSftp 用 SFTP 列远程目录（不走 agent）。
 */
export function ListSftp(host: string, dir: string): $CancellablePromise<monitor$0.FileEntry[] | null> {
    return $Call.ByID(3610524352, host, dir);
}

/**
 * LocalExistingNames 返回本机目录里已经存在的名字。给拖拽冲突弹窗用。
 */
export function LocalExistingNames(dir: string, names: string[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(3027083171, dir, names);
}

/**
 * LocalHomeDir 本机用户家目录。
 */
export function LocalHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(3741253410);
}

/**
 * NormalizeFileToLinux 将远程文本文件规范为 UTF-8（无 BOM）+ LF
 * 写前自动备份为 <file>.bak.YYYYMMDD-HHMMSS
 * 成功后返回新的预览结果（needsNormalize=false）
 */
export function NormalizeFileToLinux(host: string, file: string): $CancellablePromise<filetext$0.Preview> {
    return $Call.ByID(592903667, host, file);
}

/**
 * NormalizeLocalFileToLinux 将本机文本规范为 UTF-8（无 BOM）+ LF，写前备份。
 */
export function NormalizeLocalFileToLinux(file: string): $CancellablePromise<filetext$0.Preview> {
    return $Call.ByID(125386226, file);
}

/**
 * ReadFilePreview（Files 服务）读取远程文本文件：返回编码/换行检测 + UTF-8 内容
 * 比 ReadFileText 更完整，供预览抽屉状态栏与「转 Linux 标准」使用
 */
export function ReadFilePreview(host: string, file: string): $CancellablePromise<filetext$0.Preview> {
    return $Call.ByID(2484376929, host, file);
}

/**
 * ReadLocalFilePreview 读取本机文本文件，供 XFPT 左栏双击预览。
 */
export function ReadLocalFilePreview(file: string): $CancellablePromise<filetext$0.Preview> {
    return $Call.ByID(61953006, file);
}

/**
 * SftpCreateFile 用 SFTP 在远程创建空文件；名字已被占用时报错，不覆盖已有内容。
 */
export function SftpCreateFile(host: string, file: string): $CancellablePromise<void> {
    return $Call.ByID(2742458886, host, file);
}

/**
 * SftpExistingNames 返回远程目录里已经存在的名字。给拖拽冲突弹窗用。
 */
export function SftpExistingNames(host: string, dir: string, names: string[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(1544993891, host, dir, names);
}

/**
 * SftpHomeDir 远程登录用户家目录。
 */
export function SftpHomeDir(host: string): $CancellablePromise<string> {
    return $Call.ByID(1536006882, host);
}

/**
 * SftpMkdir 用 SFTP 在远程创建目录（不走 agent）。
 */
export function SftpMkdir(host: string, dir: string): $CancellablePromise<void> {
    return $Call.ByID(3125359735, host, dir);
}

/**
 * UploadDir 递归上传本地文件夹到远程主机，保留目录结构
 * localDir: 本地文件夹绝对路径
 * remoteDir: 远程目标目录（绝对路径，会自动创建）
 * normalize: true 时对其中「非标准文本」文件转为 UTF-8(无BOM)+LF
 */
export function UploadDir(host: string, localDir: string, remoteDir: string, normalize: boolean): $CancellablePromise<string> {
    return $Call.ByID(453272367, host, localDir, remoteDir, normalize);
}

/**
 * UploadFile 上传本地单文件到远程主机指定目录
 * localPath: 本地文件绝对路径（由 Wails 文件拖拽提供）
 * remoteDir: 远程目标目录（绝对路径，会自动创建）
 * normalize: true 时若文件是「非标准文本」则转为 UTF-8(无BOM)+LF 后再上传
 * 返回上传后的完整远程路径
 */
export function UploadFile(host: string, localPath: string, remoteDir: string, normalize: boolean): $CancellablePromise<string> {
    return $Call.ByID(1545598286, host, localPath, remoteDir, normalize);
}

/**
 * UploadPaths 批量上传多个本地路径（文件/文件夹混合）到远程目录，用于拖拽上传。
 * convertPaths: 需要「转 UTF-8(无BOM)+LF」的本地文件绝对路径集合（来自编码检查弹窗勾选）；
 * 文件夹内的文件按其绝对路径是否命中 convertPaths 决定是否转换。
 */
export function UploadPaths(host: string, localPaths: string[] | null, convertPaths: string[] | null, remoteDir: string): $CancellablePromise<void> {
    return $Call.ByID(2239550740, host, localPaths, convertPaths, remoteDir);
}

/**
 * UploadPathsAs 按冲突策略上传。mode 为 overwrite（删掉同名项再写入）或 rename（自动加「 1」「 2」）。
 */
export function UploadPathsAs(host: string, localPaths: string[] | null, remoteDir: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(1938285556, host, localPaths, remoteDir, mode);
}
