// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Groups 分组管理服务（本地存储，不修改服务器）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as groups$0 from "./internal/groups/models.js";

/**
 * AssignHost 把主机分配到分组；groupID 为空表示移出所有分组（未分组）
 */
export function AssignHost(host: string, groupID: string): $CancellablePromise<void> {
    return $Call.ByID(993611983, host, groupID);
}

/**
 * DeleteGroup 删除分组
 */
export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(507923990, id);
}

/**
 * ListGroups 返回全部分组（按 order 排序）
 */
export function ListGroups(): $CancellablePromise<groups$0.Group[] | null> {
    return $Call.ByID(2129141988);
}

/**
 * RenameGroup 重命名分组（只改显示名，保留 hosts）
 */
export function RenameGroup(id: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1936130009, id, newName);
}

/**
 * UpsertGroup 创建或更新分组
 */
export function UpsertGroup(g: groups$0.Group): $CancellablePromise<void> {
    return $Call.ByID(1043270622, g);
}
