// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Groups 分组管理服务（本地存储，不修改服务器）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as groups$0 from "./internal/groups/models.js";

/**
 * AssignHost 把主机分配到分组；groupID 为空表示移出所有分组（未分组）
 */
export function AssignHost(host: string, groupID: string): $CancellablePromise<void> {
    return $Call.ByID(993611983, host, groupID);
}

/**
 * DeleteGroup 级联删除分组及其子孙
 */
export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(507923990, id);
}

/**
 * ListGroups 返回全部分组（按 order 排序）
 */
export function ListGroups(): $CancellablePromise<groups$0.Group[] | null> {
    return $Call.ByID(2129141988);
}

/**
 * MoveGroup 将分组移到新父级；parentID 空表示升为顶层
 */
export function MoveGroup(id: string, parentID: string): $CancellablePromise<void> {
    return $Call.ByID(1787977512, id, parentID);
}

/**
 * PreviewDeleteGroup 预览级联删除影响（确认对话框用）
 */
export function PreviewDeleteGroup(id: string): $CancellablePromise<groups$0.DeleteStats> {
    return $Call.ByID(238917970, id);
}

/**
 * RenameGroup 重命名分组（只改显示名，保留 hosts）
 */
export function RenameGroup(id: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1936130009, id, newName);
}

/**
 * ReorderGroups 拖拽排序：按前端给定的同级顺序重排分组 order（依次 0,1,2…）
 */
export function ReorderGroups(parentID: string, orderedIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2321433911, parentID, orderedIDs);
}

/**
 * ReorderHosts 拖拽排序：按前端给定顺序重排分组内主机
 */
export function ReorderHosts(groupID: string, orderedNames: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3791835446, groupID, orderedNames);
}

/**
 * SetBoardTitle 设置分组看板中间标题；title 为空表示清空
 */
export function SetBoardTitle(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(285969698, id, title);
}

/**
 * SubtreeHostNames 返回分组子树内主机名
 */
export function SubtreeHostNames(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3086637332, id);
}

/**
 * UpsertGroup 创建或更新分组（可带 parentId）
 */
export function UpsertGroup(g: groups$0.Group): $CancellablePromise<void> {
    return $Call.ByID(1043270622, g);
}
