// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Hosts 主机管理服务：SSH 配置（主机增删改查 + ssh-copy-id 流程）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sshconfig$0 from "./internal/sshconfig/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddHost 添加新主机：先校验别名不重复 → 用密码连一次验证 → 推送本机公钥 → 回写 ~/.ssh/config
 * 用户只需提供别名/IP/用户/密码 4 项，端口默认 22，公钥/密钥路径自动推断为 ~/.ssh/id_ed25519(.pub)
 * 验证通过并推送公钥后，后续对该主机即可免密登录
 * 契约：四项必填；只有连通性+凭据验证成功才会写 config（由 CopySSHID 内部完成）
 */
export function AddHost(input: $models.AddHostInput): $CancellablePromise<void> {
    return $Call.ByID(2699445634, input);
}

/**
 * CopySSHID 把本机公钥安装到远程主机的 authorized_keys，并把结果写入
 * Panel JSON；OpenSSH 配置仍由 JSON 统一生成。
 * 步骤：
 *  1. 读 ~/.ssh/id_ed25519.pub（不存在则提示用户先生成）
 *  2. 用密码连一次目标主机
 *  3. 执行 mkdir -p ~/.ssh && echo "$pubkey" >> authorized_keys && chmod 限制权限
 *  4. 关闭连接
 *  5. 回写 ~/.ssh/config（追加 Host 块）
 */
export function CopySSHID(input: $models.CopyIDInput): $CancellablePromise<string> {
    return $Call.ByID(1594776111, input);
}

/**
 * DeleteHost 从 Panel JSON 删除主机别名，再生成 OpenSSH 配置，并清理分组引用与连接池
 */
export function DeleteHost(name: string): $CancellablePromise<void> {
    return $Call.ByID(83424728, name);
}

/**
 * FormatHostInfo 拼主机信息文本（含已存密码），供右键「复制信息」
 */
export function FormatHostInfo(name: string): $CancellablePromise<string> {
    return $Call.ByID(376042284, name);
}

/**
 * GetHostPassword 读取本机已保存的主机密码（供编辑弹窗预填；未保存则空串）
 */
export function GetHostPassword(name: string): $CancellablePromise<string> {
    return $Call.ByID(682744648, name);
}

/**
 * ListHosts 解析 ~/.ssh/config 返回所有 Host 条目
 * 默认过滤掉 Git 托管服务（github.com / gitee.com 等）
 * 这些通常不是用户想要管理的"服务器"
 */
export function ListHosts(): $CancellablePromise<sshconfig$0.HostConfig[] | null> {
    return $Call.ByID(1412787684);
}

/**
 * ListHostsAll 返回所有 Host 条目（包括 Git 服务）
 * 供前端「显示 Git 服务」开关使用
 */
export function ListHostsAll(): $CancellablePromise<sshconfig$0.HostConfig[] | null> {
    return $Call.ByID(2478914207);
}

/**
 * RenameHost 修改 ~/.ssh/config 里 Host 的别名
 * 同时同步 groups.json 里的引用，并关闭旧名的 SSH 连接（避免连接池残留）
 */
export function RenameHost(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(3456482961, oldName, newName);
}

/**
 * SetHostNote 仅更新本机备注（不改 ssh config、不验连；保留已存密码）
 */
export function SetHostNote(name: string, note: string): $CancellablePromise<void> {
    return $Call.ByID(1462312353, name, note);
}

/**
 * TestConnection 用密码尝试 SSH 登录（执行 hostname），仅验证连通性与凭据是否正确
 * 不推送公钥、不写 config；测试完立即关闭连接，避免污染连接池
 * 成功返回包含远程主机名的提示信息
 * 四个字段（别名/IP/用户/密码）均必填，与前端「测试通过后才能保存」契约一致
 */
export function TestConnection(input: $models.AddHostInput): $CancellablePromise<string> {
    return $Call.ByID(1288610845, input);
}

/**
 * UpdateHost 编辑主机：密码测试连通性 → 推送本机公钥 → 更新 ~/.ssh/config 中的 HostName/User
 * 别名不变；验证失败不写 config
 */
export function UpdateHost(input: $models.UpdateHostInput): $CancellablePromise<void> {
    return $Call.ByID(2265726266, input);
}
