// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Icons 主机发行版图标服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListHostIcons 读取本地已落盘的发行版记录，不访问远程
 */
export function ListHostIcons(): $CancellablePromise<$models.HostIcon[] | null> {
    return $Call.ByID(242641042);
}

/**
 * RefreshAllHostIcons 强制重新探测全部主机并更新记录
 */
export function RefreshAllHostIcons(): $CancellablePromise<$models.HostIcon[] | null> {
    return $Call.ByID(337683952);
}

/**
 * RefreshHostIcon 远程探测一台主机的发行版并落盘（强制更新）
 */
export function RefreshHostIcon(host: string): $CancellablePromise<$models.HostIcon> {
    return $Call.ByID(780289246, host);
}

/**
 * RefreshMissingHostIcons 只探测还没有图标记录的主机，已有记录直接返回
 */
export function RefreshMissingHostIcons(): $CancellablePromise<$models.HostIcon[] | null> {
    return $Call.ByID(2725931933);
}
