// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalSys 本机系统信息（macOS / Windows / Linux，不经 SSH）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as aptsource$0 from "./internal/aptsource/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localsys$0 from "./internal/localsys/models.js";

/**
 * AptSources 本机 /etc/apt 源文件 + 发行版（只读查看，仅 Linux 侧栏入口）。
 */
export function AptSources(): $CancellablePromise<aptsource$0.Snapshot | null> {
    return $Call.ByID(203772695);
}

export function Hosts(): $CancellablePromise<localsys$0.HostsInfo | null> {
    return $Call.ByID(3883088911);
}

export function Network(): $CancellablePromise<localsys$0.NetworkSnapshot | null> {
    return $Call.ByID(1558186986);
}

export function Nginx(): $CancellablePromise<localsys$0.NginxInfo | null> {
    return $Call.ByID(1569255872);
}

export function NginxRead(path: string): $CancellablePromise<string> {
    return $Call.ByID(851844372, path);
}

export function Overview(): $CancellablePromise<localsys$0.Overview | null> {
    return $Call.ByID(2549028183);
}

/**
 * PackageIcon 已安装应用图标（PNG data URL）；取不到返回空串。
 */
export function PackageIcon(path: string): $CancellablePromise<string> {
    return $Call.ByID(1509229533, path);
}

/**
 * PackageSizes 已安装应用的本体与数据占用（较慢，前端在列表出来后单独拉取）。
 */
export function PackageSizes(): $CancellablePromise<localsys$0.PackageSize[] | null> {
    return $Call.ByID(1787556450);
}

export function Packages(): $CancellablePromise<localsys$0.Package[] | null> {
    return $Call.ByID(1835217933);
}

export function StorageApps(): $CancellablePromise<localsys$0.StorageApp[] | null> {
    return $Call.ByID(2258074325);
}

export function StorageLargeFiles(): $CancellablePromise<localsys$0.StorageFile[] | null> {
    return $Call.ByID(40875483);
}

export function StorageOpenPrivacy(): $CancellablePromise<void> {
    return $Call.ByID(326183635);
}

export function StorageReveal(path: string): $CancellablePromise<void> {
    return $Call.ByID(1576277704, path);
}

export function StorageScanStart(): $CancellablePromise<localsys$0.StorageStatus | null> {
    return $Call.ByID(654020572);
}

export function StorageStatus(): $CancellablePromise<localsys$0.StorageStatus | null> {
    return $Call.ByID(4194480247);
}

export function StorageTree(path: string): $CancellablePromise<localsys$0.StorageNode | null> {
    return $Call.ByID(3569091197, path);
}
