// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalSys 本机系统信息（macOS；不经 SSH）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localsys$0 from "./internal/localsys/models.js";

export function Hosts(): $CancellablePromise<localsys$0.HostsInfo | null> {
    return $Call.ByID(3883088911);
}

export function Network(): $CancellablePromise<localsys$0.NetworkSnapshot | null> {
    return $Call.ByID(1558186986);
}

export function Nginx(): $CancellablePromise<localsys$0.NginxInfo | null> {
    return $Call.ByID(1569255872);
}

export function NginxRead(path: string): $CancellablePromise<string> {
    return $Call.ByID(851844372, path);
}

export function Overview(): $CancellablePromise<localsys$0.Overview | null> {
    return $Call.ByID(2549028183);
}

export function Packages(): $CancellablePromise<localsys$0.Package[] | null> {
    return $Call.ByID(1835217933);
}

export function StorageApps(): $CancellablePromise<localsys$0.StorageApp[] | null> {
    return $Call.ByID(2258074325);
}

export function StorageLargeFiles(): $CancellablePromise<localsys$0.StorageFile[] | null> {
    return $Call.ByID(40875483);
}

export function StorageOpenPrivacy(): $CancellablePromise<void> {
    return $Call.ByID(326183635);
}

export function StorageReveal(path: string): $CancellablePromise<void> {
    return $Call.ByID(1576277704, path);
}

export function StorageScanStart(): $CancellablePromise<localsys$0.StorageStatus | null> {
    return $Call.ByID(654020572);
}

export function StorageStatus(): $CancellablePromise<localsys$0.StorageStatus | null> {
    return $Call.ByID(4194480247);
}

export function StorageTree(path: string): $CancellablePromise<localsys$0.StorageNode | null> {
    return $Call.ByID(3569091197, path);
}
