// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalApps 本机应用监控服务（macOS / Windows / Linux 本机进程树，不经 SSH）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localapps$0 from "./internal/localapps/models.js";

/**
 * Kill 结束本机进程；force 为 true 时发送 SIGKILL。
 */
export function Kill(pid: number, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(726466945, pid, force);
}

/**
 * ProcDetail 查询单个进程详情（含线程）。
 */
export function ProcDetail(pid: number): $CancellablePromise<localapps$0.ProcNode | null> {
    return $Call.ByID(2402714440, pid);
}

/**
 * Resources 按需查询单个本机进程打开的文件描述符资源。
 */
export function Resources(pid: number): $CancellablePromise<localapps$0.ResourceSnapshot | null> {
    return $Call.ByID(3363368346, pid);
}

/**
 * Scan 扫描本机应用进程树快照。
 */
export function Scan(): $CancellablePromise<localapps$0.Snapshot | null> {
    return $Call.ByID(2913549312);
}
