// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "./internal/monitor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as panelstore$0 from "./internal/panelstore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as panelsync$0 from "./internal/panelsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wecom$0 from "./internal/wecom/models.js";

/**
 * AddHostInput 是「添加主机」对话框的入参
 * 端口默认 22，公钥/密钥路径由后端自动推断；备注与密码存本机 host_meta.json
 */
export interface AddHostInput {
    /**
     * Host 别名
     */
    "name": string;

    /**
     * IP/域名
     */
    "hostName": string;
    "user": string;

    /**
     * 必填；验连后写入 host_meta
     */
    "password": string;

    /**
     * 本机备注，可选
     */
    "note": string;
}

/**
 * AgentBatchResult 批量安装/更新单台结果
 */
export interface AgentBatchResult {
    "host": string;
    "ok": boolean;

    /**
     * 成功时安装到的版本
     */
    "version": string;
    "error"?: string;
}

/**
 * AppInfo 「关于」信息。
 */
export interface AppInfo {
    "appName": string;
    "version": string;
    "commit": string;
    "commitTime": string;
    "goVersion": string;
    "os": string;
    "arch": string;
    "agentVer": string;
    "description": string;
    "copyright": string;
    "repoUrl": string;
    "releasesUrl": string;
    "issuesUrl": string;
}

/**
 * BackupPreview 恢复前的预览信息
 */
export interface BackupPreview {
    /**
     * zip / legacy-json
     */
    "format": string;
    "version": number;
    "sourceOS": string;
    "createdAt": number;
    "hosts": number;
    "groups": number;
    "keys": number;
    "knownHosts": boolean;
    "includesPasswords": boolean;
    "newHosts": string[] | null;
    "conflicts": string[] | null;
    "droppedOptions": string[] | null;
    "keyWrites": string[] | null;
    "keyRenames": string[] | null;
}

/**
 * BoardHTTPConfig 看板 HTTP 网关配置（供前端设置页）。
 */
export interface BoardHTTPConfig {
    "enabled": boolean;
    "port": number;
}

/**
 * CertPairCheck 本地「证书 + 私钥」配对校验结果（不上传、不触网）
 */
export interface CertPairCheck {
    /**
     * 识别出的证书文件路径
     */
    "certPath": string;

    /**
     * 识别出的私钥文件路径
     */
    "keyPath": string;

    /**
     * CN + SAN 域名（去重）
     */
    "domains": string[] | null;
    "issuer": string;

    /**
     * 到期时间（Unix 秒）
     */
    "notAfter": number;

    /**
     * 剩余天数
     */
    "daysLeft": number;
    "selfSigned": boolean;
}

/**
 * ConfigDraft is used by the existing text editor. The editor submits the
 * complete config tree, which is parsed into Panel JSON and then regenerated;
 * it never becomes a second runtime source of truth.
 */
export interface ConfigDraft {
    "files": panelsync$0.ConfigFile[] | null;
}

export interface ConnectionTestResult {
    "alias": string;
    "success": boolean;
    "tested": boolean;
    "message"?: string;
    "error"?: string;
    "durationMs": number;
}

/**
 * CopyIDInput 是 CopySSHID 的入参
 */
export interface CopyIDInput {
    /**
     * Host 别名
     */
    "name": string;

    /**
     * IP/域名
     */
    "hostName": string;
    "user": string;
    "port": string;

    /**
     * 仅本次使用，不落盘（CopySSHID 本身不写 host_meta）
     */
    "password": string;

    /**
     * 默认 ~/.ssh/id_ed25519.pub
     */
    "publicKeyFile": string;

    /**
     * 写入 ssh config 的密钥路径
     */
    "identityFile": string;
}

/**
 * DesktopNotify 本机系统通知入参；Host/EventID/Kind 写入通知 Data，点击后可跳转。
 */
export interface DesktopNotify {
    "title": string;
    "body": string;
    "host"?: string;
    "eventId"?: string;

    /**
     * cpu|mem|disk|load
     */
    "kind"?: string;
}

/**
 * GroupOverview 一个分组的概览数据
 */
export interface GroupOverview {
    /**
     * 分组 ID（"__ungrouped__" 表示未分组）
     */
    "groupId": string;

    /**
     * 分组显示名
     */
    "groupName": string;
    "hosts": HostOverviewSnapshot[] | null;
}

/**
 * HostAlertNotify 面板侧资源超阈值 / 回落，或应用探活异常 / 恢复，或证书到期 / 续期入参。
 * Kind：mem | cpu | disk | load | app:<service> | cert
 */
export interface HostAlertNotify {
    "webhook": string;
    "host": string;

    /**
     * mem | cpu | disk | load | app:<service> | cert
     */
    "kind": string;

    /**
     * down = 超阈值/异常/到期, up = 已回落/恢复/续期
     */
    "state": string;
    "detail": string;

    /**
     * 证书告警的企微标题后缀；空则走原有类型文案
     */
    "titleSuffix": string;

    /**
     * 证书已过期时企微用严重，未过期用警告
     */
    "expired": boolean;

    /**
     * Title / Lines 非空时企微按「标题 + 逐行字段」输出，与系统通知、应用内同一套文案。
     */
    "title": string;
    "lines": wecom$0.Line[] | null;

    /**
     * Level 资源告警档位：warn 显示 [警告]，danger 显示 [严重]；空则按类型推断。
     */
    "level": string;
}

/**
 * HostConnNotify 面板侧主机连接告警（停机 / 恢复）入参
 */
export interface HostConnNotify {
    /**
     * 企微 webhook URL 或 key；空则跳过
     */
    "webhook": string;

    /**
     * 主机别名
     */
    "host": string;

    /**
     * down | up
     */
    "kind": string;

    /**
     * 错误原文或恢复说明
     */
    "detail": string;
}

/**
 * HostIcon 一台主机的发行版图标记录（给前端侧栏/概览用）
 */
export interface HostIcon {
    "host": string;
    "osRelease": string;
    "error"?: string;
}

/**
 * HostOverviewSnapshot 一台主机的概览快照
 */
export interface HostOverviewSnapshot {
    /**
     * Host 别名
     */
    "name": string;

    /**
     * 实际 IP/域名
     */
    "hostName": string;

    /**
     * 外网 IP（SSH 地址为公网 IP 时即它，否则取网卡公网 IP / 出口 IP）
     */
    "publicIP"?: string;

    /**
     * 内网 IP（首个私网网卡地址）
     */
    "privateIP"?: string;
    "user": string;
    "overview": monitor$0.Overview;

    /**
     * 物理盘/池(kind=disk) + 挂载分区(kind=mount)
     */
    "disks": monitor$0.DiskInfo[] | null;
    "error"?: string;

    /**
     * NotInstalled：SSH 已通，但 Agent 未装/未跑（与 SSH 掉线区分）
     */
    "notInstalled"?: boolean;
}

/**
 * ImportResult 恢复结果统计
 */
export interface ImportResult {
    "added": string[] | null;
    "overwritten": string[] | null;
    "skipped": string[] | null;
    "groups": number;
    "icons": number;
    "keys": number;
    "knownHosts": number;
    "droppedOptions": string[] | null;
}

/**
 * LocalTextCheck 单个本地文件的编码检测结果（上传前编码检查弹窗用）
 */
export interface LocalTextCheck {
    "path": string;

    /**
     * 相对路径（文件夹上传时展示层级）
     */
    "relPath": string;
    "name": string;

    /**
     * UTF-8 / GBK / GB18030 / UTF-16LE …
     */
    "encoding": string;

    /**
     * LF / CRLF / CR / Mixed
     */
    "lineEnding": string;

    /**
     * 非 Linux 标准（非 UTF-8 无 BOM + LF）
     */
    "needsNormalize": boolean;

    /**
     * 原始解码后片段（弹窗预览）
     */
    "content": string;

    /**
     * NormalizeLinux 后片段（弹窗预览对比）
     */
    "normalized": string;
    "size": number;
}

/**
 * MenuCheckResult 菜单检查：菜单是否正常、数据是否正常。
 */
export interface MenuCheckResult {
    "id": string;
    "label": string;
    "url": string;

    /**
     * 菜单正常
     */
    "ok": boolean;

    /**
     * 数据正常
     */
    "hasData": boolean;
    "menuText": string;
    "dataText": string;
    "title": string;
    "message": string;
    "checkedAt": number;
    "scheduled": boolean;
}

export interface PanelBackup {
    "summary": PanelBackupSummary;
    "state": PanelStateDraft;
    "files": PanelConfigFile[] | null;
}

export interface PanelBackupSummary {
    "id": string;
    "path": string;
    "createdAt": number;
    "revision": number;
    "hostCount": number;
    "groupCount": number;
    "fileCount": number;
    "size": number;
    "operation": string;
}

export interface PanelConfigConflict {
    "id": string;
    "kind": string;
    "file"?: string;
    "alias"?: string;
    "summary": string;
    "panel"?: string;
    "external"?: string;
    "resolved": boolean;
}

export interface PanelConfigDiff {
    "changedFiles"?: PanelConfigFileDiff[] | null;
    "addedHosts"?: string[] | null;
    "removedHosts"?: string[] | null;
    "changedHosts"?: string[] | null;
    "hostDiff"?: PanelHostDiff[] | null;
    "conflicts"?: PanelConfigConflict[] | null;
    "hasChanges": boolean;
}

/**
 * PanelConfigFile is a safe, UI-oriented file descriptor. Content is
 * returned only for files the Config Center can edit; panel.json content is
 * always redacted by the backend before it reaches the renderer.
 */
export interface PanelConfigFile {
    "path": string;
    "displayPath": string;
    "absolutePath": string;
    "mode": number;
    "size": number;
    "sha256": string;
    "updatedAt": number;
    "content": string;
    "source": string;
    "generated": boolean;
    "externalChanged": boolean;
    "panelJson": boolean;
}

export interface PanelConfigFileDiff {
    "path": string;
    "kind": string;
    "panelSha256"?: string;
    "externalSha256"?: string;
    "generatedSha256"?: string;
    "panelContent"?: string;
    "externalContent"?: string;
    "generatedContent"?: string;
}

/**
 * PanelConfigOverview is the compact state object used by the Config Center
 * landing page. The existing PanelConfigStatus remains as a compatibility
 * DTO for the settings page and older clients.
 */
export interface PanelConfigOverview {
    "panelPath": string;
    "sshConfigPath": string;
    "revision": number;
    "hostCount": number;
    "groupCount": number;
    "configFileCount": number;
    "includeCount": number;
    "configStale": boolean;
    "drift": boolean;
    "needsReview": boolean;
    "lastGenerated": number;
    "lastBackup"?: PanelBackupSummary | null;
    "diff": PanelConfigDiff;
}

export interface PanelConfigPreview {
    "previewId": string;
    "baseRevision": number;
    "baseConfigHash": string;
    "affectedHosts"?: string[] | null;
    "connectionTests"?: ConnectionTestResult[] | null;
    "fileDiff"?: PanelConfigFileDiff[] | null;
    "hostDiff"?: PanelHostDiff[] | null;
    "conflicts"?: PanelConfigConflict[] | null;
    "valid": boolean;
    "source": string;
    "error"?: string;
    "expiresAt": number;
}

export interface PanelConfigResolution {
    "id": string;

    /**
     * panel, external, manual
     */
    "choice": string;
    "manual"?: string;
}

export interface PanelConfigStatus {
    "panelPath": string;
    "sshConfigPath": string;
    "revision": number;
    "configStale": boolean;
    "drift": boolean;
    "needsReview": boolean;
    "diff": panelsync$0.ConfigDiff;
}

export interface PanelHostDiff {
    "alias": string;
    "kind": string;
    "fields"?: string[] | null;
    "panel"?: string;
    "candidate"?: string;
}

/**
 * PanelHostDraft intentionally does not expose the system-owned fields in
 * panelstore.PanelHost. A masked password is merged with the current secret
 * server-side; the mask is never written to panel.json.
 */
export interface PanelHostDraft {
    "alias": string;
    "hostName": string;
    "user": string;
    "port"?: string;
    "password"?: string;
    "identityFiles"?: string[] | null;
    "proxyJump"?: string;
    "proxyCommand"?: string;
    "identityAgent"?: string;
    "forwardAgent"?: boolean;
    "hostKeyAlgos"?: string;
    "portForwards"?: panelstore$0.PortForward[] | null;
    "note"?: string;
    "groupId"?: string;
    "order"?: number;
    "extraOptions"?: panelstore$0.SSHOption[] | null;
}

export interface PanelStateDraft {
    "hosts": PanelHostDraft[] | null;
    "groups": panelstore$0.PanelGroup[] | null;
    "extraOptions"?: panelstore$0.SSHOption[] | null;
}

/**
 * PanelSystemEditor is a safe, user-facing description of an installed
 * editor. The frontend sends only ID back to the backend; it never supplies a
 * process path or shell command.
 */
export interface PanelSystemEditor {
    "id": string;
    "name": string;
    "path": string;
    "installed": boolean;
    "systemDefault": boolean;
}

/**
 * UpdateHostInput 是「编辑主机」对话框的入参
 * 别名不可在此接口修改（请用 RenameHost）；须带密码做连通性验证，通过后才写 config
 */
export interface UpdateHostInput {
    /**
     * 现有 Host 别名
     */
    "name": string;

    /**
     * 新 IP/域名
     */
    "hostName": string;

    /**
     * 登录用户
     */
    "user": string;

    /**
     * 必填；验连后写入 host_meta
     */
    "password": string;

    /**
     * 本机备注，可选
     */
    "note": string;
}

export interface WindowThemeState {
    "preference": string;
    "effective": string;
    "supported": boolean;
    "reason": string;
    "revision": number;
}
