// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as groups$0 from "./internal/groups/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hosticon$0 from "./internal/hosticon/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "./internal/monitor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sshconfig$0 from "./internal/sshconfig/models.js";

/**
 * AddHostInput 是「添加主机」对话框的入参（用户只需填 4 项）
 * 端口默认 22，公钥/密钥路径由后端自动推断
 */
export interface AddHostInput {
    /**
     * Host 别名
     */
    "name": string;

    /**
     * IP/域名
     */
    "hostName": string;
    "user": string;

    /**
     * 仅本次使用，不落盘
     */
    "password": string;
}

/**
 * AgentBatchResult 批量安装/更新单台结果
 */
export interface AgentBatchResult {
    "host": string;
    "ok": boolean;

    /**
     * 成功时安装到的版本
     */
    "version": string;
    "error"?: string;
}

/**
 * BackupData 备份文件内容：主机列表 + 分组 + 主机图标记录
 * 注意：SSH 私钥不在备份内，换机恢复需另行保管 ~/.ssh/id_ed25519
 */
export interface BackupData {
    "version": number;
    "exportedAt": number;
    "hosts": sshconfig$0.HostConfig[] | null;
    "groups": groups$0.Group[] | null;
    "icons": hosticon$0.Record[] | null;
}

/**
 * CertPairCheck 本地「证书 + 私钥」配对校验结果（不上传、不触网）
 */
export interface CertPairCheck {
    /**
     * 识别出的证书文件路径
     */
    "certPath": string;

    /**
     * 识别出的私钥文件路径
     */
    "keyPath": string;

    /**
     * CN + SAN 域名（去重）
     */
    "domains": string[] | null;
    "issuer": string;

    /**
     * 到期时间（Unix 秒）
     */
    "notAfter": number;

    /**
     * 剩余天数
     */
    "daysLeft": number;
    "selfSigned": boolean;
}

/**
 * CopyIDInput 是 CopySSHID 的入参
 */
export interface CopyIDInput {
    /**
     * Host 别名
     */
    "name": string;

    /**
     * IP/域名
     */
    "hostName": string;
    "user": string;
    "port": string;

    /**
     * 仅本次使用，不落盘
     */
    "password": string;

    /**
     * 默认 ~/.ssh/id_ed25519.pub
     */
    "publicKeyFile": string;

    /**
     * 写入 ssh config 的密钥路径
     */
    "identityFile": string;
}

/**
 * GroupOverview 一个分组的概览数据
 */
export interface GroupOverview {
    /**
     * 分组 ID（"__ungrouped__" 表示未分组）
     */
    "groupId": string;

    /**
     * 分组显示名
     */
    "groupName": string;
    "hosts": HostOverviewSnapshot[] | null;
}

/**
 * HostIcon 一台主机的发行版图标记录（给前端侧栏/概览用）
 */
export interface HostIcon {
    "host": string;
    "osRelease": string;
    "error"?: string;
}

/**
 * HostOverviewSnapshot 一台主机的概览快照
 */
export interface HostOverviewSnapshot {
    /**
     * Host 别名
     */
    "name": string;

    /**
     * 实际 IP/域名
     */
    "hostName": string;
    "user": string;
    "overview": monitor$0.Overview;

    /**
     * 仅保留根分区一行（用于卡片显示）
     */
    "disks": monitor$0.DiskInfo[] | null;
    "error"?: string;
}

/**
 * ImportResult 导入结果统计
 */
export interface ImportResult {
    /**
     * 新增的主机别名
     */
    "added": string[] | null;

    /**
     * 覆盖的主机别名
     */
    "overwritten": string[] | null;

    /**
     * 跳过的已存在主机
     */
    "skipped": string[] | null;

    /**
     * 导入/合并的分组数
     */
    "groups": number;

    /**
     * 写入的图标记录数
     */
    "icons": number;
}

/**
 * LocalTextCheck 单个本地文件的编码检测结果（上传前编码检查弹窗用）
 */
export interface LocalTextCheck {
    "path": string;

    /**
     * 相对路径（文件夹上传时展示层级）
     */
    "relPath": string;
    "name": string;

    /**
     * UTF-8 / GBK / GB18030 / UTF-16LE …
     */
    "encoding": string;

    /**
     * LF / CRLF / CR / Mixed
     */
    "lineEnding": string;

    /**
     * 非 Linux 标准（非 UTF-8 无 BOM + LF）
     */
    "needsNormalize": boolean;

    /**
     * 原始解码后片段（弹窗预览）
     */
    "content": string;

    /**
     * NormalizeLinux 后片段（弹窗预览对比）
     */
    "normalized": string;
    "size": number;
}

/**
 * UpdateHostInput 是「编辑主机」对话框的入参
 * 别名不可在此接口修改（请用 RenameHost）；须带密码做连通性验证，通过后才写 config
 */
export interface UpdateHostInput {
    /**
     * 现有 Host 别名
     */
    "name": string;

    /**
     * 新 IP/域名
     */
    "hostName": string;

    /**
     * 登录用户
     */
    "user": string;

    /**
     * 仅本次使用，不落盘
     */
    "password": string;
}
