// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Monitor 监控采集服务（只读）。
 * 全部数据经 SSH 隧道读取目标主机上的 spanel-agent（HTTP over direct-tcpip），
 * 面板不再经 SSH 频繁执行采集命令；方法签名与返回结构与历史版本保持一致，前端零改动。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentcli$0 from "./internal/agentcli/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as aptsource$0 from "./internal/aptsource/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "./internal/monitor/models.js";

/**
 * CollectAptSources 远程 /etc/apt 源文件 + 发行版（只读查看）。
 */
export function CollectAptSources(host: string): $CancellablePromise<aptsource$0.Snapshot> {
    return $Call.ByID(986192323, host);
}

/**
 * CollectCertCheck 读取 spanel-agent 留下的证书日检快照（不在面板侧临时扫 openssl）。
 * 旧版 agent 没有该端点时返回错误，调用方应跳过，不要当成「没有证书」。
 */
export function CollectCertCheck(host: string): $CancellablePromise<agentcli$0.CertCheckSnapshot> {
    return $Call.ByID(499353682, host);
}

/**
 * CollectCerts 识别远程主机 /etc/nginx/cert 下的证书（目录不存在时 installed=false）
 */
export function CollectCerts(host: string): $CancellablePromise<monitor$0.CertListResult> {
    return $Call.ByID(1939004723, host);
}

/**
 * CollectCrons 定时任务列表
 */
export function CollectCrons(host: string): $CancellablePromise<monitor$0.Cron[] | null> {
    return $Call.ByID(934073661, host);
}

/**
 * CollectDisks 磁盘分区列表
 */
export function CollectDisks(host: string): $CancellablePromise<monitor$0.DiskInfo[] | null> {
    return $Call.ByID(1015297578, host);
}

/**
 * CollectDocker Docker 容器列表与 stats
 */
export function CollectDocker(host: string): $CancellablePromise<monitor$0.DockerInfo> {
    return $Call.ByID(678997332, host);
}

/**
 * CollectHosts 目标主机 /etc/hosts（只读，解析后条目 + 原文）
 */
export function CollectHosts(host: string): $CancellablePromise<monitor$0.HostsInfo> {
    return $Call.ByID(1615812787, host);
}

/**
 * CollectJava Java 进程列表
 */
export function CollectJava(host: string): $CancellablePromise<monitor$0.ProcInfo[] | null> {
    return $Call.ByID(2083577472, host);
}

/**
 * CollectJavaProcDetail 单个 Java 进程详情（jstack/jmap 摘要）
 */
export function CollectJavaProcDetail(host: string, pid: number): $CancellablePromise<monitor$0.JavaProcDetail> {
    return $Call.ByID(3486184409, host, pid);
}

/**
 * CollectLargestFiles 扫描指定挂载点 Top N 大文件（可能较慢，勿阻塞 UI）
 */
export function CollectLargestFiles(host: string, root: string, limit: number): $CancellablePromise<monitor$0.LargeFilesResult> {
    return $Call.ByID(3256134655, host, root, limit);
}

/**
 * CollectLog 读取指定类型日志的末尾 N 行
 * logType: system / auth / kernel / nginx_access / nginx_error
 */
export function CollectLog(host: string, logType: string, lines: number): $CancellablePromise<monitor$0.LogResult> {
    return $Call.ByID(483060930, host, logType, lines);
}

/**
 * CollectNetwork 网络快照（网卡/连接/监听端口）
 */
export function CollectNetwork(host: string): $CancellablePromise<monitor$0.NetworkSnapshot> {
    return $Call.ByID(3656978470, host);
}

/**
 * CollectOverview 顶层系统指标：agent 持续采集的最新采样 + 静态信息，读库零命令
 */
export function CollectOverview(host: string): $CancellablePromise<monitor$0.Overview> {
    return $Call.ByID(1867124547, host);
}

/**
 * CollectPackageDepends 单个软件包的直接依赖名列表（按需查询，兼容旧 agent 列表无 depList）
 */
export function CollectPackageDepends(host: string, pkgName: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2129095583, host, pkgName);
}

/**
 * CollectPackages apt 包列表（重查询）
 */
export function CollectPackages(host: string): $CancellablePromise<monitor$0.AptPackage[] | null> {
    return $Call.ByID(271399513, host);
}

/**
 * CollectProcesses 进程列表（CPU 排序 Top N）
 */
export function CollectProcesses(host: string, limit: number): $CancellablePromise<monitor$0.ProcInfo[] | null> {
    return $Call.ByID(1251867617, host, limit);
}

/**
 * CollectRuntimeCounts 各运行时进程计数
 */
export function CollectRuntimeCounts(host: string): $CancellablePromise<monitor$0.RuntimeCounts> {
    return $Call.ByID(65980104, host);
}

/**
 * CollectRuntimeProcs 指定运行时（java/go/node…）的进程列表
 */
export function CollectRuntimeProcs(host: string, runtime: string): $CancellablePromise<monitor$0.RuntimeProc[] | null> {
    return $Call.ByID(967926837, host, runtime);
}

/**
 * CollectRuntimes 运行时版本（java/go/node/python…）
 */
export function CollectRuntimes(host: string): $CancellablePromise<monitor$0.RuntimeInfo[] | null> {
    return $Call.ByID(1976963749, host);
}

/**
 * CollectServiceDetail 查询单个 systemd 服务的详情（服务页悬浮卡片按需调用）
 */
export function CollectServiceDetail(host: string, name: string): $CancellablePromise<monitor$0.ServiceDetail> {
    return $Call.ByID(187826658, host, name);
}

/**
 * CollectServices systemd 服务列表
 */
export function CollectServices(host: string): $CancellablePromise<monitor$0.Service[] | null> {
    return $Call.ByID(418272960, host);
}

/**
 * DeletePaths 删除远程主机上的多个文件或目录（递归，不可恢复）。
 * 路径必须是绝对路径；系统根目录（/、/etc、/usr 等）禁止删除（agent 侧同样校验）。
 */
export function DeletePaths(host: string, paths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(730712899, host, paths);
}

/**
 * DockerAction 对容器执行 start/stop/restart 等操作
 */
export function DockerAction(host: string, action: string, container: string): $CancellablePromise<string> {
    return $Call.ByID(1861137480, host, action, container);
}

/**
 * DockerInspect 查询单个容器的 docker inspect 原始 JSON（Docker 页悬浮卡片按需调用）
 */
export function DockerInspect(host: string, container: string): $CancellablePromise<string> {
    return $Call.ByID(1684742510, host, container);
}

/**
 * GetHomeDir 返回远程登录用户的家目录（$HOME）。
 * 文件管理器默认打开此路径；agent 以 root 运行时即 /root。
 */
export function GetHomeDir(host: string): $CancellablePromise<string> {
    return $Call.ByID(3580994260, host);
}

/**
 * KillProcess 在远程主机上杀掉指定 PID
 */
export function KillProcess(host: string, pid: number, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(332040671, host, pid, force);
}

/**
 * ListDir 列出远程主机某目录下的内容（只读，不修改）
 */
export function ListDir(host: string, dir: string): $CancellablePromise<monitor$0.FileEntry[] | null> {
    return $Call.ByID(255385153, host, dir);
}

/**
 * ReadFileText 读远程文本文件内容（最多 512KB，只读）
 */
export function ReadFileText(host: string, file: string): $CancellablePromise<string> {
    return $Call.ByID(4024224535, host, file);
}
