// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Monitor 监控采集服务（只读）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "./internal/monitor/models.js";

/**
 * CollectCerts 识别远程主机 /etc/nginx/cert 下的证书（目录不存在时 installed=false）
 */
export function CollectCerts(host: string): $CancellablePromise<monitor$0.CertListResult> {
    return $Call.ByID(1939004723, host);
}

export function CollectCrons(host: string): $CancellablePromise<monitor$0.Cron[] | null> {
    return $Call.ByID(934073661, host);
}

export function CollectDisks(host: string): $CancellablePromise<monitor$0.DiskInfo[] | null> {
    return $Call.ByID(1015297578, host);
}

export function CollectDocker(host: string): $CancellablePromise<monitor$0.DockerInfo> {
    return $Call.ByID(678997332, host);
}

export function CollectJava(host: string): $CancellablePromise<monitor$0.ProcInfo[] | null> {
    return $Call.ByID(2083577472, host);
}

/**
 * CollectJavaProcDetail 单个 Java 进程的补充详情（悬浮卡片按需查询）
 */
export function CollectJavaProcDetail(host: string, pid: number): $CancellablePromise<monitor$0.JavaProcDetail> {
    return $Call.ByID(3486184409, host, pid);
}

/**
 * CollectLargestFiles 异步场景：扫描指定挂载点 Top N 大文件（可能较慢，勿阻塞 UI）
 */
export function CollectLargestFiles(host: string, root: string, limit: number): $CancellablePromise<monitor$0.LargeFilesResult> {
    return $Call.ByID(3256134655, host, root, limit);
}

/**
 * CollectLog 读取指定类型日志的末尾 N 行
 * logType: system / auth / kernel / nginx_access / nginx_error
 */
export function CollectLog(host: string, logType: string, lines: number): $CancellablePromise<monitor$0.LogResult> {
    return $Call.ByID(483060930, host, logType, lines);
}

/**
 * CollectNetwork 网卡 / IP 分类 / TCP 连接 / 疑似卡顿连接
 */
export function CollectNetwork(host: string): $CancellablePromise<monitor$0.NetworkSnapshot> {
    return $Call.ByID(3656978470, host);
}

/**
 * CollectOverview 采集顶层系统指标（按需/手动刷新，不做秒级轮询落盘）
 */
export function CollectOverview(host: string): $CancellablePromise<monitor$0.Overview> {
    return $Call.ByID(1867124547, host);
}

export function CollectPackages(host: string): $CancellablePromise<monitor$0.AptPackage[] | null> {
    return $Call.ByID(271399513, host);
}

export function CollectProcesses(host: string, limit: number): $CancellablePromise<monitor$0.ProcInfo[] | null> {
    return $Call.ByID(1251867617, host, limit);
}

/**
 * CollectRuntimeCounts 各运行时（java/go/node/bun/python）正在运行的进程数
 * 进程页顶部标签的数字徽标，轻量轮询
 */
export function CollectRuntimeCounts(host: string): $CancellablePromise<monitor$0.RuntimeCounts> {
    return $Call.ByID(65980104, host);
}

/**
 * CollectRuntimeProcs 采集指定运行时（java/go/node/bun/python）的进程列表
 * 含部署方式/端口/入口（jar/脚本/可执行文件），进程页各运行时视图主列表
 */
export function CollectRuntimeProcs(host: string, runtime: string): $CancellablePromise<monitor$0.RuntimeProc[] | null> {
    return $Call.ByID(967926837, host, runtime);
}

/**
 * CollectRuntimes 识别常用运行环境版本（java/go/python/node/bun）
 */
export function CollectRuntimes(host: string): $CancellablePromise<monitor$0.RuntimeInfo[] | null> {
    return $Call.ByID(1976963749, host);
}

/**
 * CollectServiceDetail 查询单个 systemd 服务的详情（服务页悬浮卡片按需调用）
 */
export function CollectServiceDetail(host: string, name: string): $CancellablePromise<monitor$0.ServiceDetail> {
    return $Call.ByID(187826658, host, name);
}

export function CollectServices(host: string): $CancellablePromise<monitor$0.Service[] | null> {
    return $Call.ByID(418272960, host);
}

/**
 * DeletePaths 删除远程主机上的多个文件或目录（递归，不可恢复）
 * 路径必须是绝对路径；系统根目录（/、/etc、/usr 等）禁止删除
 */
export function DeletePaths(host: string, paths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(730712899, host, paths);
}

/**
 * DockerAction 对容器执行 start/stop/restart 等操作
 */
export function DockerAction(host: string, action: string, container: string): $CancellablePromise<string> {
    return $Call.ByID(1861137480, host, action, container);
}

/**
 * DockerInspect 查询单个容器的 docker inspect 原始 JSON（Docker 页悬浮卡片按需调用）
 */
export function DockerInspect(host: string, container: string): $CancellablePromise<string> {
    return $Call.ByID(1684742510, host, container);
}

/**
 * GetHomeDir 返回远程登录用户的家目录（$HOME）。
 * 文件管理器默认打开此路径，而不是系统根 /。
 * 远程查询失败时按 SSH User 回退：root → /root，其它 → /home/<user>。
 */
export function GetHomeDir(host: string): $CancellablePromise<string> {
    return $Call.ByID(3580994260, host);
}

/**
 * KillProcess 在远程主机上杀掉指定 PID
 */
export function KillProcess(host: string, pid: number, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(332040671, host, pid, force);
}

/**
 * ListDir 列出远程主机某目录下的内容（只读，不修改）
 */
export function ListDir(host: string, dir: string): $CancellablePromise<monitor$0.FileEntry[] | null> {
    return $Call.ByID(255385153, host, dir);
}

/**
 * ReadFileText 读远程文本文件内容（最多 512KB，只读）
 */
export function ReadFileText(host: string, file: string): $CancellablePromise<string> {
    return $Call.ByID(4024224535, host, file);
}
