// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotifySubs 通知订阅（资源告警 / 应用探活 / 企微通道），落盘到本机应用数据目录。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifysubs$0 from "./internal/notifysubs/models.js";

/**
 * Get 读取已保存的订阅。FromDisk=false 表示尚未落盘，前端可把 localStorage 迁过来。
 */
export function Get(): $CancellablePromise<notifysubs$0.Data> {
    return $Call.ByID(4294364358);
}

/**
 * Set 整份覆盖并落盘。重编译应用后仍在。
 */
export function Set(d: notifysubs$0.Data): $CancellablePromise<void> {
    return $Call.ByID(729343210, d);
}
