// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Overview 分组概览服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListGroupOverview 采集所有分组的所有主机概览（较慢，慎用）
 * 并发上限 5；单台失败不拖垮其它主机
 */
export function ListGroupOverview(): $CancellablePromise<$models.GroupOverview[] | null> {
    return $Call.ByID(917179619);
}

/**
 * ListOneGroupOverview 只采集指定分组，避免「打开一个分组却扫全库」导致长时间加载中
 */
export function ListOneGroupOverview(groupID: string): $CancellablePromise<$models.GroupOverview> {
    return $Call.ByID(1478451225, groupID);
}
