// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PanelConfig is the JSON/config synchronization service. It is deliberately
 * separate from Hosts: Hosts owns the ordinary host UI, while this service is
 * the explicit boundary between Panel JSON and the external OpenSSH tree.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as panelstore$0 from "./internal/panelstore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as panelsync$0 from "./internal/panelsync/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CommitPanelPreview(previewID: string): $CancellablePromise<panelsync$0.WriteResult> {
    return $Call.ByID(694489423, previewID);
}

export function CompareConfig(): $CancellablePromise<panelsync$0.ConfigDiff> {
    return $Call.ByID(3932135501);
}

/**
 * ConfirmConfigImport explicitly accepts an ambiguous external config diff.
 * The accepted tree becomes the new JSON snapshot, but remains config-stale
 * until the normal generation path re-tests every host and runs ssh -G.
 */
export function ConfirmConfigImport(): $CancellablePromise<panelsync$0.ImportResult> {
    return $Call.ByID(1362058979);
}

export function GenerateConfig(): $CancellablePromise<panelsync$0.WriteResult> {
    return $Call.ByID(2941527997);
}

export function GetConfigFiles(): $CancellablePromise<panelsync$0.ConfigFile[] | null> {
    return $Call.ByID(3717926941);
}

export function GetConfigText(): $CancellablePromise<string> {
    return $Call.ByID(1353663537);
}

export function GetConfigTree(): $CancellablePromise<$models.PanelConfigFile[] | null> {
    return $Call.ByID(626073750);
}

export function GetEditablePanelState(): $CancellablePromise<$models.PanelStateDraft> {
    return $Call.ByID(1654904547);
}

/**
 * GetEditablePanelStateSensitive is intentionally separate from the normal
 * editor endpoint. The UI calls it only for an explicit, temporary reveal and
 * immediately discards the returned plaintext when the view is left.
 */
export function GetEditablePanelStateSensitive(): $CancellablePromise<$models.PanelStateDraft> {
    return $Call.ByID(3943824721);
}

export function GetOverview(): $CancellablePromise<$models.PanelConfigOverview> {
    return $Call.ByID(1389874607);
}

export function GetPanelBackup(id: string): $CancellablePromise<$models.PanelBackup> {
    return $Call.ByID(1546127260, id);
}

export function GetPanelState(): $CancellablePromise<panelstore$0.State> {
    return $Call.ByID(4243863839);
}

export function GetStatus(): $CancellablePromise<$models.PanelConfigStatus> {
    return $Call.ByID(504493142);
}

/**
 * ImportConfig imports non-conflicting external edits into Panel JSON. It
 * does not immediately rewrite the config: the next Panel save/generation is
 * the point at which the JSON model becomes the generated artifact again.
 */
export function ImportConfig(): $CancellablePromise<panelsync$0.ImportResult> {
    return $Call.ByID(2508437983);
}

export function ListPanelBackups(): $CancellablePromise<$models.PanelBackupSummary[] | null> {
    return $Call.ByID(2012052777);
}

/**
 * ListSystemEditors returns the installed applications that Panel can safely
 * launch for a controlled config path. Discovery is performed on every call
 * so an editor installed or removed while Panel is running is reflected in
 * the picker immediately.
 */
export function ListSystemEditors(): $CancellablePromise<$models.PanelSystemEditor[] | null> {
    return $Call.ByID(1852712141);
}

export function OpenPanelPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1806248061, path);
}

/**
 * OpenPanelPathWithEditor opens a controlled Panel file in an editor selected
 * from ListSystemEditors. The editor ID is resolved again on the backend so a
 * caller cannot turn this into an arbitrary command or path launcher.
 */
export function OpenPanelPathWithEditor(path: string, editorID: string): $CancellablePromise<void> {
    return $Call.ByID(333285236, path, editorID);
}

export function PreviewConfigDraft(draft: $models.ConfigDraft): $CancellablePromise<$models.PanelConfigPreview> {
    return $Call.ByID(2943227281, draft);
}

export function PreviewPanelState(draft: $models.PanelStateDraft): $CancellablePromise<$models.PanelConfigPreview> {
    return $Call.ByID(1635309479, draft);
}

export function ResolveConfigConflicts(previewID: string, resolutions: $models.PanelConfigResolution[] | null): $CancellablePromise<$models.PanelConfigPreview> {
    return $Call.ByID(2937924561, previewID, resolutions);
}

export function RestorePanelBackup(id: string): $CancellablePromise<panelsync$0.WriteResult> {
    return $Call.ByID(3330858814, id);
}

export function RevealPanelPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(734304150, path);
}

/**
 * SaveConfigDraft parses a complete editor draft into JSON, then force-generates
 * the formal config from that JSON. This is the only supported "save" path for
 * text editing, so a manual config edit cannot create a second live model.
 */
export function SaveConfigDraft(draft: $models.ConfigDraft): $CancellablePromise<panelsync$0.WriteResult> {
    return $Call.ByID(4178675402, draft);
}

/**
 * SaveState replaces the JSON draft and runs the same validation, connectivity
 * and ssh -G checks as a normal generation. A failed generation leaves the
 * JSON saved and marks it config-stale for a later retry.
 */
export function SaveState(state: panelstore$0.State): $CancellablePromise<void> {
    return $Call.ByID(1071863118, state);
}

/**
 * TestHost is the explicit connectivity gate for the JSON editor. It tests
 * the JSON fields directly and does not read OpenSSH config.
 */
export function TestHost(host: panelstore$0.PanelHost): $CancellablePromise<string> {
    return $Call.ByID(3368253734, host);
}
