// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SpeedTest 网络测速服务（内置 iperf3）：路径识别、两机测速、分组测速与历史。
 * 进度与实时采样经 speedtest-state / speedtest-sample / speedtest-batch 事件推送。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as speedtest$0 from "./internal/speedtest/models.js";

/**
 * ActiveID 当前进行中的任务 ID（无则空）
 */
export function ActiveID(): $CancellablePromise<string> {
    return $Call.ByID(2641547022);
}

/**
 * DeleteHistory 删除一条记录；id 为空时清空
 */
export function DeleteHistory(id: string): $CancellablePromise<void> {
    return $Call.ByID(4289839342, id);
}

/**
 * DetectPaths 识别 A、B 之间的局域网 / 广域网路径（实测连通）；port 为 0 时自动
 */
export function DetectPaths(a: string, b: string, port: number): $CancellablePromise<speedtest$0.PathReport> {
    return $Call.ByID(1747493290, a, b, port);
}

/**
 * GetHistory 单条完整记录（含采样 / 分组轮次）
 */
export function GetHistory(id: string): $CancellablePromise<speedtest$0.Record> {
    return $Call.ByID(1866015869, id);
}

/**
 * ListHistory 历史列表（新在前，不含采样）
 */
export function ListHistory(): $CancellablePromise<speedtest$0.HistoryItem[] | null> {
    return $Call.ByID(215958407);
}

/**
 * LocalID 「本机」端点的保留 ID
 */
export function LocalID(): $CancellablePromise<string> {
    return $Call.ByID(1689368777);
}

/**
 * Start 启动两机测速，返回任务 ID
 */
export function Start(req: speedtest$0.StartRequest): $CancellablePromise<string> {
    return $Call.ByID(243390595, req);
}

/**
 * StartGroup 启动分组测速（星型 / 全互测矩阵），返回任务 ID
 */
export function StartGroup(req: speedtest$0.GroupRequest): $CancellablePromise<string> {
    return $Call.ByID(3177939514, req);
}

/**
 * Stop 停止进行中的任务
 */
export function Stop(id: string): $CancellablePromise<void> {
    return $Call.ByID(1593405457, id);
}
