// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * System 系统服务：内置脚本上传 / 窗口控制等
 * SetTrafficLightsHidden / SetFrostedChrome 见 system.go
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "./internal/monitor/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BootstrapZsh 把内置的 zsh 初始化脚本上传到远程主机 /tmp,返回远程路径。
 * 实际执行交给前端终端(实时显示输出),执行完由终端命令清理临时脚本。
 */
export function BootstrapZsh(host: string): $CancellablePromise<string> {
    return $Call.ByID(3099666800, host);
}

/**
 * CloseBoardWindow 按 groupID 关闭对应看板窗；groupID 为空则无操作（须显式传分组）。
 */
export function CloseBoardWindow(groupID: string): $CancellablePromise<void> {
    return $Call.ByID(2474462435, groupID);
}

/**
 * FocusMainWindow 显示并聚焦主窗口（看板双击主机后切回主窗操作）。
 * 从后台挂起恢复时先把 Dock 图标加回来（Regular），再出示窗口。
 */
export function FocusMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(2479596072);
}

/**
 * GetMyEgress 查询本机出口公网 IP 与归属地（来自 myip.ipip.net）
 * 用于设置页本机信息。不依赖任何主机。
 */
export function GetMyEgress(): $CancellablePromise<monitor$0.EgressInfo> {
    return $Call.ByID(772990904);
}

/**
 * NotifyDesktop 本机系统通知（Wails 原生通知中心）。
 * 未获授权时静默空操作；点击通知会 FocusMainWindow 并 Emit alert-open-host。
 */
export function NotifyDesktop($in: $models.DesktopNotify): $CancellablePromise<void> {
    return $Call.ByID(3415807530, $in);
}

/**
 * NotifyHostAlert 面板检测到 CPU/内存/磁盘/负载超阈值或回落、以及应用探活异常/恢复时发企微。
 */
export function NotifyHostAlert($in: $models.HostAlertNotify): $CancellablePromise<void> {
    return $Call.ByID(3629648658, $in);
}

/**
 * NotifyHostConn 面板检测到主机连接失败 / 恢复时发送企微告警。
 * 与 agent 侧 jar 探活告警共用同一 webhook 与 markdown 版式。
 */
export function NotifyHostConn($in: $models.HostConnNotify): $CancellablePromise<void> {
    return $Call.ByID(1135117834, $in);
}

/**
 * OpenBoardWindow 打开或聚焦该分组的看板窗（普通尺寸，不立刻全屏、不调进程级 kiosk）。
 * 同分组重复调用只聚焦已有窗；不同分组各自一窗，互不影响。
 */
export function OpenBoardWindow(groupID: string): $CancellablePromise<void> {
    return $Call.ByID(1404223385, groupID);
}

/**
 * SetFrostedChrome 热切换主窗与全部看板窗的磨砂材质。
 * 开启：透明底 + macOS Visual Effect；关闭：主窗 RGB(244,244,244)、看板 RGB(15,17,21)。
 */
export function SetFrostedChrome(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4058646694, enabled);
}

/**
 * SetTrafficLightsHidden 隐藏/恢复 macOS 窗口红绿灯按钮
 * 供前端卡片最大化时调用：最大化期间隐藏，退出时恢复。
 * v3 原生支持按钮状态控制（替代 v2 的 cgo/AppKit 实现）。
 */
export function SetTrafficLightsHidden(hidden: boolean): $CancellablePromise<void> {
    return $Call.ByID(2375721563, hidden);
}

/**
 * TestWecomWebhook 向企业微信群机器人发一条测试消息，确认地址可用。
 * 空地址或企微拒绝时返回错误；前端据此决定能否保存新地址。
 */
export function TestWecomWebhook(webhook: string): $CancellablePromise<void> {
    return $Call.ByID(1547119601, webhook);
}
