// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * System 系统服务：内置脚本上传 / 窗口控制等
 * SetTrafficLightsHidden 见 system.go
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "./internal/monitor/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginTerminalTransfer 暂停指定 PTY 的流输出并保存短暂的跨 WebView 交接数据。
 * 在目标 WebView 完成接管前，输出只进入该 sid 的隔离缓冲，不会落到旧窗或丢弃。
 */
export function BeginTerminalTransfer(payload: $models.TerminalTransfer): $CancellablePromise<string> {
    return $Call.ByID(3822273739, payload);
}

/**
 * BootstrapZsh 把内置的 zsh 初始化脚本上传到远程主机 /tmp,返回远程路径。
 * 实际执行交给前端终端(实时显示输出),执行完由终端命令清理临时脚本。
 */
export function BootstrapZsh(host: string): $CancellablePromise<string> {
    return $Call.ByID(3099666800, host);
}

/**
 * CancelTerminalTransfer 交接失败或超时，恢复原 sid 的输出流。
 */
export function CancelTerminalTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(2553071470, id);
}

/**
 * CheckMenuPage 立即用 Go HTTP 检查菜单项（不打开浏览器）。id 空则检查全部，返回最后一项结果以兼容旧调用。
 */
export function CheckMenuPage(id: string): $CancellablePromise<$models.MenuCheckResult> {
    return $Call.ByID(3866735965, id);
}

/**
 * CloseBoardWindow 按 groupID 关闭对应看板窗；groupID 为空则无操作（须显式传分组）。
 */
export function CloseBoardWindow(groupID: string): $CancellablePromise<void> {
    return $Call.ByID(2474462435, groupID);
}

/**
 * CompleteTerminalTransfer 目标 WebView 已挂载 xterm 和流通道后提交交接。
 */
export function CompleteTerminalTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3182140959, id);
}

/**
 * FocusMainWindow 显示并聚焦主窗口（看板双击主机后切回主窗操作）。
 * 从后台挂起恢复时先把 Dock 图标加回来（Regular），再出示窗口。
 */
export function FocusMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(2479596072);
}

/**
 * FocusTerminalWindow 恢复一个被隐藏的终端窗口，不创建新会话或新窗口。
 */
export function FocusTerminalWindow(windowID: string): $CancellablePromise<void> {
    return $Call.ByID(1822908189, windowID);
}

/**
 * GetAskBeforeQuit ⌘Q / 应用菜单退出前是否先确认（挂后台或彻底退出）。
 */
export function GetAskBeforeQuit(): $CancellablePromise<boolean> {
    return $Call.ByID(289649498);
}

/**
 * GetMyEgress 查询本机出口公网 IP 与归属地（来自 myip.ipip.net）
 * 用于设置页本机信息。不依赖任何主机。
 */
export function GetMyEgress(): $CancellablePromise<monitor$0.EgressInfo> {
    return $Call.ByID(772990904);
}

/**
 * HideTerminalWindow 隐藏指定终端窗，但不销毁 WebView 或终端会话。
 */
export function HideTerminalWindow(windowID: string): $CancellablePromise<void> {
    return $Call.ByID(3259950667, windowID);
}

/**
 * ListMenuChecks 返回内置菜单检查项及最近一次结果。
 */
export function ListMenuChecks(): $CancellablePromise<$models.MenuCheckResult[] | null> {
    return $Call.ByID(1424624473);
}

/**
 * ListTerminalWindows 返回当前进程内创建过的终端原生窗口。
 * 窗口关闭时只是隐藏，因此前端可以用它提供「恢复窗口」入口。
 */
export function ListTerminalWindows(): $CancellablePromise<$models.TerminalWindowInfo[] | null> {
    return $Call.ByID(3811268512);
}

/**
 * NotifyDesktop 本机系统通知（Wails 原生通知中心）。
 * 未获授权时静默空操作；点击通知会 FocusMainWindow 并 Emit alert-open-host。
 */
export function NotifyDesktop($in: $models.DesktopNotify): $CancellablePromise<void> {
    return $Call.ByID(3415807530, $in);
}

/**
 * NotifyHostAlert 面板检测到 CPU/内存/磁盘/负载超阈值或回落、应用探活异常/恢复、证书到期/续期时发企微。
 */
export function NotifyHostAlert($in: $models.HostAlertNotify): $CancellablePromise<void> {
    return $Call.ByID(3629648658, $in);
}

/**
 * NotifyHostConn 面板检测到主机连接失败 / 恢复时发送企微告警。
 * 与 agent 侧 jar 探活告警共用同一 webhook 与 markdown 版式。
 */
export function NotifyHostConn($in: $models.HostConnNotify): $CancellablePromise<void> {
    return $Call.ByID(1135117834, $in);
}

/**
 * OpenBoardWindow 打开或聚焦该分组的看板窗（普通尺寸，不立刻全屏、不调进程级 kiosk）。
 * 同分组重复调用只聚焦已有窗；不同分组各自一窗，互不影响。
 */
export function OpenBoardWindow(groupID: string): $CancellablePromise<void> {
    return $Call.ByID(1404223385, groupID);
}

/**
 * OpenTerminalWindow 仅由用户明确选择新窗口或拖拽终端时调用。
 * WindowID 为空时创建新的终端窗；指定 WindowID 时复用已有窗口，把动作投递过去。
 */
export function OpenTerminalWindow(command: $models.TerminalWindowCommand): $CancellablePromise<void> {
    return $Call.ByID(2063293391, command);
}

/**
 * SetAskBeforeQuit 设置「退出前询问」；与确认框内勾选写入同一份配置。
 */
export function SetAskBeforeQuit(ask: boolean): $CancellablePromise<void> {
    return $Call.ByID(1165354974, ask);
}

/**
 * SetThemeAppearance 同步窗口原生外观。应用已固定亮色主题：
 * 无论传入什么值（历史前端仍可能传 dark/auto），一律按 light 处理。
 */
export function SetThemeAppearance(_mode: string): $CancellablePromise<void> {
    return $Call.ByID(474639928, _mode);
}

/**
 * SetTrafficLightsHidden 隐藏/恢复 macOS 窗口红绿灯按钮
 * 供前端卡片最大化时调用：最大化期间隐藏，退出时恢复。
 * v3 原生支持按钮状态控制（替代 v2 的 cgo/AppKit 实现）。
 */
export function SetTrafficLightsHidden(hidden: boolean): $CancellablePromise<void> {
    return $Call.ByID(2375721563, hidden);
}

/**
 * TakeTerminalTransfer 由目标 WebView领取交接数据；领取本身不会释放输出缓冲。
 */
export function TakeTerminalTransfer(id: string): $CancellablePromise<$models.TerminalTransfer> {
    return $Call.ByID(2802882943, id);
}

/**
 * TerminalWindowReady 标记某个终端 WebView 已挂载，并领取创建期间暂存的动作。
 */
export function TerminalWindowReady(windowID: string): $CancellablePromise<$models.TerminalWindowCommand[] | null> {
    return $Call.ByID(4272466850, windowID);
}

/**
 * TestWecomWebhook 向企业微信群机器人发一条测试消息，确认地址可用。
 * 空地址或企微拒绝时返回错误；前端据此决定能否保存新地址。
 */
export function TestWecomWebhook(webhook: string): $CancellablePromise<void> {
    return $Call.ByID(1547119601, webhook);
}
