// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalSvc 终端服务（PTY 会话）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseTerminal(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1583452746, sessionID);
}

/**
 * OpenTerminal 打开一个终端会话（Events 模式，作为 WS 通道不可用时的回退）
 * eventName 是前端订阅输出的 Wails 事件名
 * cols/rows 为 xterm fit 后的真实行列，开 PTY 时就用正确尺寸，避免开局乱码
 */
export function OpenTerminal(host: string, eventName: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(2917989910, host, eventName, cols, rows);
}

/**
 * OpenTerminalWS 打开一个 WS 模式终端会话（低延迟数据通道）
 * 输入输出走 localhost WebSocket 二进制帧；Resize / Close 频率低，仍走绑定方法
 */
export function OpenTerminalWS(host: string, cols: number, rows: number): $CancellablePromise<$models.TermWSInfo> {
    return $Call.ByID(2531311616, host, cols, rows);
}

/**
 * ResizeTerminal 通知终端会话窗口大小变化（cols/rows）
 * 前端 xterm 的 fit.addon 计算出行列数后调用此方法，后端通过 ioctl 同步给 PTY
 */
export function ResizeTerminal(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(851559362, sessionID, cols, rows);
}

export function WriteTerminal(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(94455525, sessionID, data);
}
