// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalSvc 终端服务（PTY 会话）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function CloseTerminal(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1583452746, sessionID);
}

/**
 * DisconnectHost 断开主机的全部连接：关闭该主机所有终端会话（独立连接一并释放），
 * 再关闭连接池中该主机的连接。前端关闭主机标签时调用。
 */
export function DisconnectHost(host: string): $CancellablePromise<void> {
    return $Call.ByID(3951750474, host);
}

/**
 * OpenTerminal 打开一个终端会话（独立 SSH 连接 + 本地流优先、Wails 事件兜底）
 * eventName 是前端订阅输出的 Wails 事件名
 * cols/rows 为 xterm fit 后的真实行列，开 PTY 时就用正确尺寸，避免开局乱码
 */
export function OpenTerminal(host: string, eventName: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(2917989910, host, eventName, cols, rows);
}

/**
 * ResizeTerminal 通知终端会话窗口大小变化（cols/rows）
 * 前端 xterm 的 fit.addon 计算出行列数后调用此方法，后端通过 ioctl 同步给 PTY
 */
export function ResizeTerminal(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(851559362, sessionID, cols, rows);
}

/**
 * TermStreamEndpoint 返回本地终端流服务公共地址（JSON：base + token）。
 * 前端在每个 PTY sid 建立独立双向 WebSocket，绕开 Wails 主线程通道；
 * 拿不到或连接失败时自动回退 wails 事件/binding 通道。
 */
export function TermStreamEndpoint(): $CancellablePromise<string> {
    return $Call.ByID(3165377181);
}

export function WriteTerminal(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(94455525, sessionID, data);
}
