// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Data 通知订阅与通道（与前端 settings 对齐）。
 * 落盘到系统应用数据目录，重编译 / 换 webview 不会丢。
 */
export interface Data {
    /**
     * FromDisk 本次 Get 是否来自已有文件（false = 尚未落盘，前端可把 localStorage 迁过来）
     */
    "fromDisk": boolean;
    "notifyEnabled": boolean;
    "wecomWebhook": string;
    "systemNotifyEnabled": boolean;
    "inAppNotifyEnabled": boolean;
    "alertContentKinds": string[] | null;
    "notifyRecoverEnabled": boolean;
    "notifyContentFields": string[] | null;
    "hostResourceNotifySubs": { [_ in string]?: string[] | null } | null;
    "hostAppNotifySubs": { [_ in string]?: string[] | null } | null;
}
