// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Data 通知订阅与通道（与前端 settings 对齐）。
 * 落盘到系统应用数据目录，重编译 / 换 webview 不会丢。
 */
export interface Data {
    /**
     * FromDisk 本次 Get 是否来自已有文件（false = 尚未落盘，前端可把 localStorage 迁过来）
     */
    "fromDisk": boolean;
    "notifyEnabled": boolean;
    "wecomWebhook": string;
    "systemNotifyEnabled": boolean;
    "inAppNotifyEnabled": boolean;
    "alertContentKinds": string[] | null;
    "notifyRecoverEnabled": boolean;

    /**
     * AlertLevels 资源指标（cpu/mem/disk/load）订阅的档位，可同时订 warn 和 danger。
     */
    "alertLevels": { [_ in string]?: string[] | null } | null;

    /**
     * AlertSustain 连续几次采样达标才推送（1–12）；AlertRepeatMinutes 未回落时每隔几分钟重复提醒（0 = 不重复）。
     */
    "alertSustain": number;
    "alertRepeatMinutes": number;

    /**
     * load1 | load5 | load15
     */
    "alertLoadWindow": string;
    "notifyContentFields": string[] | null;
    "hostResourceNotifySubs": { [_ in string]?: string[] | null } | null;
    "hostAppNotifySubs": { [_ in string]?: string[] | null } | null;

    /**
     * HostCertNotifySubs 按主机订阅证书到期。true 才发；缺省或 false 不发。
     */
    "hostCertNotifySubs": { [_ in string]?: boolean } | null;

    /**
     * CertKindMigrated 旧配置已补过「证书」总闸。缺省时加载一次并打开，之后尊重用户关掉。
     */
    "certKindMigrated": boolean;
}
