// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemFont 一个字体家族。
 */
export interface SystemFont {
    "family": string;
    "monospace": boolean;
}
