// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeleteStats 级联删除统计（供确认文案）
 */
export interface DeleteStats {
    /**
     * 将删除的分组数（含自身）
     */
    "groupCount": number;

    /**
     * 将回到未分组的主机数（子树去重）
     */
    "hostCount": number;
}

/**
 * Group 表示一个服务器分组（ParentID 空为顶层；MaxDepth=1 时不允许嵌套）
 */
export interface Group {
    /**
     * 分组唯一 ID
     */
    "id": string;

    /**
     * 分组显示名
     */
    "name": string;

    /**
     * 父分组 ID；空 = 顶层
     */
    "parentId"?: string;

    /**
     * 看板模式中间标题（可空）
     */
    "boardTitle"?: string;

    /**
     * 同级排序权重
     */
    "order": number;

    /**
     * 该节点直接包含的 Host 名称
     */
    "hosts": string[] | null;
}
