// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Group 表示一个服务器分组
 */
export interface Group {
    /**
     * 分组唯一 ID（UUID）
     */
    "id": string;

    /**
     * 分组显示名
     */
    "name": string;

    /**
     * 看板模式中间标题（可空）
     */
    "boardTitle"?: string;

    /**
     * 排序权重
     */
    "order": number;

    /**
     * 该分组包含的 Host 名称
     */
    "hosts": string[] | null;
}
