// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentEvent /events 事件
 */
export interface AgentEvent {
    "ts": number;
    "level": string;
    "msg": string;
}

/**
 * AppShutdownReq POST /op/app-shutdown
 */
export interface AppShutdownReq {
    "service": string;
    "pid": number;
    "port": number;
    "screen": string;
}

/**
 * AppShutdownResult POST /op/app-shutdown 响应
 */
export interface AppShutdownResult {
    "ok": boolean;
    "stopped": boolean;
    "msg": string;
}

/**
 * CurrentPoint 最新采样
 */
export interface CurrentPoint {
    "ts": number;
    "cpuPercent": number;
    "load1": number;
    "load5": number;
    "load15": number;
    "memUsed": number;
    "memTotal": number;
    "swapUsed": number;
    "swapTotal": number;
    "netRxBytes": number;
    "netTxBytes": number;
    "netRxKBps": number;
    "netTxKBps": number;
    "diskReadBytes": number;
    "diskWriteBytes": number;
    "diskReadKBps": number;
    "diskWriteKBps": number;
    "diskIOCount": number;
    "diskUsed": number;
    "diskTotal": number;
}

/**
 * CurrentResponse /metrics/current 响应
 */
export interface CurrentResponse {
    "metrics": CurrentPoint;
    "info": HostInfo;
}

/**
 * Health /health 响应
 */
export interface Health {
    "version": string;
    "uptimeSec": number;
    "rssKB": number;
    "cpuTimeSec": number;
    "writtenSamples": number;
    "droppedSamples": number;
    "lastWriteErr": string;
    "diskLow": boolean;
}

/**
 * HostInfo 静态主机信息
 */
export interface HostInfo {
    "hostname": string;
    "arch": string;
    "kernel": string;
    "osRelease": string;
    "cpuModel": string;
    "cpuCount": number;
    "ipAddress": string;
    "uptime": number;
    "collectedAt": number;
}

/**
 * JarRangePoint /watch/range 点
 */
export interface JarRangePoint {
    "ts": number;
    "service": string;
    "pid": number;
    "port": number;
    "rss": number;
    "cpuPercent": number;
    "heapUsed": number;
    "heapMax": number;
    "gcPauseMs": number;
    "healthOk": boolean;
}

/**
 * JavaAppInstance /watch/instances 单 Java 实例
 */
export interface JavaAppInstance {
    "service": string;
    "runtime": string;
    "pid": number;
    "port": number;
    "deployVer": string;
    "startTime": string;
    "screen": string;
    "jarPath": string;
    "healthUp": boolean;
    "processUp": boolean;
    "ingressUp": boolean;
    "ingressOn": boolean;
    "status": string;
    "group": string;
}

/**
 * RangePoint /metrics/range 数据点
 */
export interface RangePoint {
    "ts": number;
    "cpuPercent": number;
    "load1": number;
    "memUsed": number;
    "netRxKBps": number;
    "netTxKBps": number;
    "diskReadKBps": number;
    "diskWriteKBps": number;
}

/**
 * RangeResponse /metrics/range 响应
 */
export interface RangeResponse {
    "src": string;
    "points": RangePoint[] | null;
}

/**
 * Status 缓存的 agent 状态（主机列表徽章用）
 */
export interface Status {
    "ok": boolean;
    "version": string;
    "rssKB": number;

    /**
     * OK=false 时的原因摘要
     */
    "error"?: string;
    "notInstalled"?: boolean;
    "checkedAt": string;
}

/**
 * SummaryRange /metrics/summary 单窗口摘要
 */
export interface SummaryRange {
    "name": string;
    "cpuAvg": number;
    "cpuMax": number;
    "load1Max": number;
    "memUsedMax": number;
}

/**
 * WatchEventRow /watch/events
 */
export interface WatchEventRow {
    "ts": number;
    "service": string;
    "layer": string;
    "kind": string;
    "msg": string;
}

/**
 * WatchRangeResponse /watch/range
 */
export interface WatchRangeResponse {
    "points": JarRangePoint[] | null;
}

/**
 * WatchStatus /watch/status 单服务
 */
export interface WatchStatus {
    "service": string;
    "runtime": string;
    "processUp": boolean;
    "healthUp": boolean;
    "ingressUp": boolean;
    "ingressOn": boolean;
    "instances": number;
}

/**
 * WatchYAML /admin/watch
 */
export interface WatchYAML {
    "yaml": string;
}
