// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentapi$0 from "../agentapi/models.js";

export type AgentEvent = agentapi$0.AgentEvent;

export type AppShutdownReq = agentapi$0.AppShutdownReq;

export type AppShutdownResult = agentapi$0.AppShutdownResult;

export type CertCheckSnapshot = agentapi$0.CertCheckSnapshot;

/**
 * CheckItem 一项检查结果
 */
export interface CheckItem {
    "key": string;
    "name": string;
    "ok": boolean;
    "detail": string;
}

/**
 * CheckReport agent 自检报告（服务 / 通信 / 版本 / 采集）
 */
export interface CheckReport {
    "ok": boolean;
    "summary": string;
    "items": CheckItem[] | null;
}

export type CurrentResponse = agentapi$0.CurrentResponse;

export type Health = agentapi$0.Health;

export type JavaAppInstance = agentapi$0.JavaAppInstance;

export type RangeResponse = agentapi$0.RangeResponse;

/**
 * Status 缓存的 agent 状态（主机列表徽章用）
 */
export interface Status {
    "ok": boolean;
    "version": string;
    "rssKB": number;

    /**
     * OK=false 时的原因摘要
     */
    "error"?: string;
    "notInstalled"?: boolean;
    "checkedAt": string;
}

export type SummaryRange = agentapi$0.SummaryRange;

export type WatchEventRow = agentapi$0.WatchEvent;

export type WatchRangeResponse = agentapi$0.WatchRangeResponse;

export type WatchStatus = agentapi$0.WatchStatus;

export type WatchYAML = agentapi$0.WatchYAML;
