// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigFile stores the last known raw content of a config file. Keeping the
 * raw snapshot in the Panel model lets the generator preserve comments and
 * unknown directives while still rendering managed Host blocks from JSON.
 */
export interface ConfigFile {
    "path": string;
    "content": string;
    "mode"?: number;
    "sha256"?: string;
}

export interface ConfigLayout {
    "files"?: ConfigFile[] | null;
    "generatedFiles"?: string[] | null;
    "managedHosts"?: string[] | null;
    "lastGenerated"?: number;
}

export interface PanelGroup {
    "id": string;
    "name": string;
    "parentId"?: string;
    "boardTitle"?: string;
    "order": number;
    "color"?: string;
}

export interface PanelHost {
    "alias": string;
    "hostName": string;
    "user": string;
    "port"?: string;
    "password"?: string;
    "identityFiles"?: string[] | null;
    "proxyJump"?: string;
    "proxyCommand"?: string;
    "identityAgent"?: string;
    "forwardAgent"?: boolean;
    "hostKeyAlgos"?: string;
    "portForwards"?: PortForward[] | null;
    "note"?: string;
    "groupId"?: string;
    "order"?: number;
    "extraOptions"?: SSHOption[] | null;
}

export interface PortForward {
    "kind": string;
    "bind"?: string;
    "port"?: string;
    "target"?: string;
    "targetPort"?: string;
}

export interface SSHOption {
    "key": string;
    "value": string;
}

export interface State {
    "version": number;
    "revision": number;
    "updatedAt": number;
    "configStale"?: boolean;
    "lastError"?: string;
    "hosts": PanelHost[] | null;
    "groups": PanelGroup[] | null;
    "configLayout"?: ConfigLayout;
    "extraOptions"?: SSHOption[] | null;
}
