// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Line 企微正文的一行「标签: 值」
 */
export interface Line {
    "label": string;
    "value": string;
}
