// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Event 一条应用内告警历史（资源超阈 / 回落）。
 */
export interface Event {
    "id": string;
    "host": string;

    /**
     * cpu|mem|disk|load
     */
    "kind": string;

    /**
     * down|up
     */
    "state": string;
    "title": string;
    "detail": string;

    /**
     * unix ms
     */
    "at": number;
    "read": boolean;
}
