// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentEvent /events 事件
 */
export interface AgentEvent {
    "ts": number;

    /**
     * info / warn / error
     */
    "level": string;
    "msg": string;
}

/**
 * AppShutdownReq POST /op/app-shutdown
 */
export interface AppShutdownReq {
    "service": string;
    "pid": number;
    "port": number;
    "screen": string;
}

/**
 * AppShutdownResult POST /op/app-shutdown 响应
 */
export interface AppShutdownResult {
    "ok": boolean;
    "stopped": boolean;
    "msg": string;
}

/**
 * CertBrief 证书检查快照里的一张证书（与 /collect/certs 的字段对齐，只留告警要用的）。
 */
export interface CertBrief {
    "name": string;
    "domains": string[] | null;
    "issuer": string;

    /**
     * 到期时间（Unix 秒）
     */
    "notAfter": number;

    /**
     * 扫描当时的剩余天数（负数 = 已过期）
     */
    "daysLeft": number;
}

/**
 * CertCheckSnapshot spanel-agent 每天一次的 /etc/nginx/cert 扫描结果。
 * Scanned=false 表示今天还没扫过（例如进程在凌晨 6 点前启动，正在等到点）。
 */
export interface CertCheckSnapshot {
    "scanned": boolean;

    /**
     * 主机本地日期 YYYY-MM-DD
     */
    "localDate": string;

    /**
     * Unix 秒
     */
    "scannedAt": number;

    /**
     * 目录是否存在
     */
    "installed": boolean;

    /**
     * 远程缺少 openssl，无法解析
     */
    "noOpenssl": boolean;

    /**
     * ParseFailed 目录里有非私钥文件没解析成证书。不当成证书已删除。
     */
    "parseFailed": boolean;
    "certs": CertBrief[] | null;
}

/**
 * CurrentPoint 最新一条采样（/metrics/current 的动态部分）
 */
export interface CurrentPoint {
    "ts": number;
    "cpuPercent": number;
    "load1": number;
    "load5": number;
    "load15": number;
    "memUsed": number;
    "memTotal": number;
    "swapUsed": number;
    "swapTotal": number;
    "netRxBytes": number;
    "netTxBytes": number;
    "netRxKBps": number;
    "netTxKBps": number;
    "diskReadBytes": number;
    "diskWriteBytes": number;
    "diskReadKBps": number;
    "diskWriteKBps": number;
    "diskIOCount": number;
    "diskUsed": number;
    "diskTotal": number;
}

/**
 * CurrentResponse /metrics/current 响应
 */
export interface CurrentResponse {
    "metrics": CurrentPoint;
    "info": HostInfo;
}

/**
 * Health /health 响应
 */
export interface Health {
    "version": string;
    "uptimeSec": number;

    /**
     * 自身常驻内存
     */
    "rssKB": number;

    /**
     * 自身累计 CPU 时间（秒）
     */
    "cpuTimeSec": number;
    "writtenSamples": number;
    "droppedSamples": number;
    "lastWriteErr": string;
    "diskLow": boolean;
}

/**
 * HostInfo 变化频率低的主机信息
 */
export interface HostInfo {
    "hostname": string;
    "arch": string;
    "kernel": string;
    "osRelease": string;
    "cpuModel": string;
    "cpuCount": number;
    "ipAddress": string;

    /**
     * 秒
     */
    "uptime": number;

    /**
     * 本信息采集时间（Unix 秒）
     */
    "collectedAt": number;
}

/**
 * JarRangePoint /watch/range 点
 */
export interface JarRangePoint {
    "ts": number;
    "service": string;
    "pid": number;
    "port": number;
    "rss": number;
    "cpuPercent": number;
    "heapUsed": number;
    "heapMax": number;
    "gcPauseMs": number;
    "healthOk": boolean;
}

/**
 * JavaAppInstance /watch/instances 单 Java 实例
 */
export interface JavaAppInstance {
    "service": string;

    /**
     * java / bun
     */
    "runtime": string;
    "pid": number;
    "port": number;
    "deployVer": string;

    /**
     * 该 jar 所在服务目录下最新日期版本
     */
    "latestDeployVer": string;
    "startTime": string;
    "screen": string;
    "jarPath": string;
    "healthUp": boolean;
    "processUp": boolean;
    "ingressUp": boolean;
    "ingressOn": boolean;

    /**
     * UP / DOWN / UNHEALTHY
     */
    "status": string;

    /**
     * std / pro / other
     */
    "group": string;
}

/**
 * RangePoint 历史序列统一数据点（raw 与 agg 两种来源都折算成它）
 */
export interface RangePoint {
    "ts": number;
    "cpuPercent": number;
    "load1": number;
    "memUsed": number;
    "netRxKBps": number;
    "netTxKBps": number;
    "diskReadKBps": number;
    "diskWriteKBps": number;
}

/**
 * RangeResponse /metrics/range 响应
 */
export interface RangeResponse {
    "src": string;
    "points": RangePoint[] | null;
}

/**
 * SummaryRange 一个时间窗的摘要
 */
export interface SummaryRange {
    /**
     * 1h / 6h / 24h / 7d
     */
    "name": string;
    "cpuAvg": number;
    "cpuMax": number;
    "load1Max": number;
    "memUsedMax": number;
}

/**
 * WatchEvent 分层探活状态变化（/watch/events）
 */
export interface WatchEvent {
    "ts": number;
    "service": string;

    /**
     * process / health / ingress
     */
    "layer": string;

    /**
     * down / up
     */
    "kind": string;
    "msg": string;
}

/**
 * WatchRangeResponse /watch/range
 */
export interface WatchRangeResponse {
    "points": JarRangePoint[] | null;
}

/**
 * WatchStatus /watch/status 单服务
 */
export interface WatchStatus {
    "service": string;
    "runtime": string;
    "processUp": boolean;
    "healthUp": boolean;
    "ingressUp": boolean;
    "ingressOn": boolean;
    "instances": number;
}

/**
 * WatchYAML /admin/watch
 */
export interface WatchYAML {
    "yaml": string;
}
