// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as panelstore$0 from "../panelstore/models.js";

export interface ConfigDiff {
    "changedFiles"?: string[] | null;
    "addedHosts"?: string[] | null;
    "removedHosts"?: string[] | null;
    "changedHosts"?: string[] | null;
    "conflicts"?: string[] | null;
}

export interface ConfigFile {
    "path": string;
    "content": string;
    "mode"?: number;
    "sha256"?: string;
}

export interface ImportResult {
    "state": panelstore$0.State;
    "diff": ConfigDiff;
    "needsReview": boolean;
}

/**
 * WriteResult describes the durable side effects of a generation. The backup
 * is created before any config file is replaced, so a failed multi-file write
 * still leaves a recoverable point-in-time snapshot.
 */
export interface WriteResult {
    "backupPath": string;
    "files": ConfigFile[] | null;
    "removed"?: string[] | null;
}
