// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Distro 从 /etc/os-release 解析出的发行版。
 */
export interface Distro {
    "id": string;
    "name": string;
    "version": string;
    "codename": string;
    "apt": boolean;
}

/**
 * File 一份 apt 源文件。
 */
export interface File {
    "name": string;
    "path": string;
    "size": number;
    "content": string;
}

/**
 * Snapshot GET /collect/apt-sources
 */
export interface Snapshot {
    "distro": Distro;
    "files": File[] | null;
}
