// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApplyResult POST /op/apt-apply 响应
 */
export interface ApplyResult {
    "backupDir": string;
    "mirror": string;
    "name": string;
    "changed": number;
    "updateOut": string;
}

/**
 * Distro 从 /etc/os-release 解析出的发行版。
 */
export interface Distro {
    "id": string;
    "name": string;
    "version": string;
    "codename": string;
    "apt": boolean;
}

/**
 * File 一份 apt 源文件。
 */
export interface File {
    "name": string;
    "path": string;
    "size": number;
    "content": string;
}

/**
 * ProbeHit 单个镜像测速结果。
 */
export interface ProbeHit {
    "id": string;
    "name": string;
    "host": string;
    "ok": boolean;
    "ms": number;
    "error"?: string;
}

/**
 * Snapshot GET /collect/apt-sources
 */
export interface Snapshot {
    "distro": Distro;
    "files": File[] | null;
}
