// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostConfig 表示一个 SSH 主机配置条目
 */
export interface HostConfig {
    /**
     * Host 名称（别名）
     */
    "name": string;

    /**
     * 实际主机/IP
     */
    "hostName": string;

    /**
     * 登录用户
     */
    "user": string;

    /**
     * 端口（默认 22）
     */
    "port": string;

    /**
     * 密钥路径
     */
    "identityFile": string;

    /**
     * 跳板机
     */
    "proxyJump": string;

    /**
     * 原文保留（部分场景需要）
     */
    "hostKeyAlgos": string;

    /**
     * Note 本机备注：存 Application Support 的 host_meta.json，不写入 ~/.ssh/config；
     * 列表/导出时由 Hosts 服务合并进来。
     */
    "note"?: string;

    /**
     * Password 本机保存的登录密码：仅备份导出/导入时出现在此结构体；
     * 不写入 ~/.ssh/config，也不随 ListHosts 下发。
     */
    "password"?: string;
}
