// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostConfig 表示一个 SSH 主机配置条目
 */
export interface HostConfig {
    /**
     * Host 名称（别名）
     */
    "name": string;

    /**
     * 实际主机/IP
     */
    "hostName": string;

    /**
     * 登录用户
     */
    "user": string;

    /**
     * 端口（默认 22）
     */
    "port": string;

    /**
     * 密钥路径
     */
    "identityFile": string;

    /**
     * 跳板机
     */
    "proxyJump": string;

    /**
     * 原文保留（部分场景需要）
     */
    "hostKeyAlgos": string;
}
