// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Session 一次应用进程的运行记录（启动 → 退出）。
 */
export interface Session {
    "id": string;

    /**
     * unix ms
     */
    "startAt": number;

    /**
     * unix ms；0 表示仍在运行
     */
    "endAt": number;

    /**
     * unix ms；心跳时间，异常退出时作为退出时间
     */
    "lastSeenAt": number;

    /**
     * 结束后写入
     */
    "durationSec": number;

    /**
     * normal|abnormal；运行中为空
     */
    "endReason": string;
    "version": string;
}
