// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProbeInfo 安装前探测（架构、systemd、磁盘水位、内存、写权限）
 */
export interface ProbeInfo {
    /**
     * uname -m
     */
    "Arch": string;

    /**
     * uname -s
     */
    "OS": string;
    "HasSystemd": boolean;

    /**
     * systemd：PID 1 是 systemd；supervisor：容器 / OpenRC / sysvinit 等，走自带守护循环
     */
    "InitMode": string;

    /**
     * 有 crontab，守护方式可挂 @reboot + 每分钟 ensure
     */
    "HasCron": boolean;

    /**
     * 有 rc-update，守护方式可挂 local.d 开机自启
     */
    "HasOpenRC": boolean;
    "HasBinary": boolean;

    /**
     * active / inactive / failed / not-found
     */
    "ServiceState": string;
    "DataMount": string;
    "DataTotalKB": number;
    "DataAvailKB": number;
    "TmpAvailKB": number;
    "BinAvailKB": number;
    "MemTotalKB": number;
    "MemAvailKB": number;
    "UID": number;
    "WritableBin": boolean;
    "WritableTmp": boolean;
}
