// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProbeInfo 安装前探测
 */
export interface ProbeInfo {
    /**
     * uname -m
     */
    "Arch": string;

    /**
     * 是否有 systemctl
     */
    "HasSystemd": boolean;

    /**
     * /usr/local/bin/spanel-agent 是否存在
     */
    "HasBinary": boolean;

    /**
     * active / inactive / not-found（not-found = 未安装服务）
     */
    "ServiceState": string;
}
