// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProbeInfo 安装前探测（架构、systemd、磁盘水位、内存、写权限）
 */
export interface ProbeInfo {
    /**
     * uname -m
     */
    "Arch": string;

    /**
     * uname -s
     */
    "OS": string;
    "HasSystemd": boolean;
    "HasBinary": boolean;

    /**
     * active / inactive / failed / not-found
     */
    "ServiceState": string;
    "DataMount": string;
    "DataTotalKB": number;
    "DataAvailKB": number;
    "TmpAvailKB": number;
    "BinAvailKB": number;
    "MemTotalKB": number;
    "MemAvailKB": number;
    "UID": number;
    "WritableBin": boolean;
    "WritableTmp": boolean;
}
