/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentInstallDialog: typeof import('./components/AgentInstallDialog.vue')['default']
    AlertEventList: typeof import('./components/alert/AlertEventList.vue')['default']
    BackupImportDialog: typeof import('./components/BackupImportDialog.vue')['default']
    BoardModeOverlay: typeof import('./components/board/BoardModeOverlay.vue')['default']
    BoardSparkline: typeof import('./components/board/BoardSparkline.vue')['default']
    BoardWindowApp: typeof import('./components/board/BoardWindowApp.vue')['default']
    DistroLogo: typeof import('./components/DistroLogo.vue')['default']
    EditHostDialog: typeof import('./components/sidebar/EditHostDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EncodeCheckDialog: typeof import('./components/files/EncodeCheckDialog.vue')['default']
    EnlargableCard: typeof import('./components/EnlargableCard.vue')['default']
    FileFolderIcon: typeof import('./components/FileFolderIcon.vue')['default']
    FilePreviewDrawer: typeof import('./components/files/FilePreviewDrawer.vue')['default']
    FileTable: typeof import('./components/files/FileTable.vue')['default']
    HostBoardCard: typeof import('./components/board/HostBoardCard.vue')['default']
    HostContextMenu: typeof import('./components/sidebar/HostContextMenu.vue')['default']
    LargestFilesDialog: typeof import('./components/LargestFilesDialog.vue')['default']
    RouterButton: typeof import('./components/RouterButton.vue')['default']
    TagButton: typeof import('./components/TagButton.vue')['default']
    UploadProgressDialog: typeof import('./components/files/UploadProgressDialog.vue')['default']
    VChartLine: typeof import('./components/VChartLine.vue')['default']
    VChartPie: typeof import('./components/VChartPie.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
