// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    CPUCoreStat,
    DiskInfo,
    HostEntry,
    HostsInfo,
    NetInterface,
    NetworkSnapshot,
    NginxFile,
    NginxInfo,
    Overview,
    Package,
    ReportItem,
    ReportRow,
    ReportSection,
    Runtime,
    StorageApp,
    StorageAppPart,
    StorageFile,
    StorageNode,
    StorageStatus,
    SystemReport
} from "./models.js";
