// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CPUCoreStat 单个逻辑核使用率。
 * Kind: "perf" | "eff" | ""（无 P/E 拓扑或超出划分范围时为空）。
 */
export interface CPUCoreStat {
    "index": number;
    "percent": number;
    "kind": string;
}

/**
 * DiskInfo 磁盘卷或物理容器。
 */
export interface DiskInfo {
    "mount": string;
    "device": string;
    "filesystem": string;
    "fsType": string;
    "total": number;
    "used": number;
    "free": number;
    "avail": number;
    "percent": number;

    /**
     * disk=物理容器；mount=挂载卷
     */
    "kind": string;

    /**
     * 物理盘键：如 disk3；外置可与 mount 同键
     */
    "parent": string;
}

/**
 * HostEntry 解析后的 hosts 行。
 */
export interface HostEntry {
    "ip": string;
    "names": string[] | null;
    "comment": string;
    "disabled": boolean;
    "raw": string;
}

/**
 * HostsInfo /etc/hosts 内容。
 */
export interface HostsInfo {
    "raw": string;
    "entries": HostEntry[] | null;
}

/**
 * NetInterface 网卡。
 */
export interface NetInterface {
    "name": string;

    /**
     * hardware port 名，如 Wi-Fi
     */
    "display": string;

    /**
     * wifi / ethernet / thunderbolt / vpn / other
     */
    "kind": string;

    /**
     * up / down
     */
    "state": string;
    "mtu": number;
    "mac": string;
    "ipv4": string;
    "ipv6": string;
    "rxBytes": number;
    "txBytes": number;
}

/**
 * NetworkSnapshot 本机网络摘要（不做连接表）。
 */
export interface NetworkSnapshot {
    "interfaces": NetInterface[] | null;
    "privateIPs": string[] | null;
    "defaultGateway": string;
    "primaryIP": string;
    "primaryIface": string;
}

/**
 * NginxFile 配置文件条目（不含内容）。
 */
export interface NginxFile {
    "name": string;
    "path": string;
    "size": number;
}

/**
 * NginxInfo Nginx 配置概览。
 */
export interface NginxInfo {
    "installed": boolean;
    "running": boolean;
    "version": string;
    "confPath": string;
    "confDir": string;
    "files": NginxFile[] | null;
}

/**
 * Overview 本机系统概览（字段对齐 monitor.Overview，便于前端复用环图）。
 */
export interface Overview {
    "cpuPercent": number;
    "memPercent": number;
    "memTotal": number;
    "memUsed": number;
    "swapPercent": number;
    "swapTotal": number;
    "swapUsed": number;
    "load1": number;
    "load5": number;
    "load15": number;
    "uptime": number;
    "kernel": string;
    "osRelease": string;
    "cpuCount": number;
    "cpuModel": string;

    /**
     * 性能核心（Apple Silicon）；0 表示无区分
     */
    "perfCores": number;

    /**
     * 能效核心
     */
    "effCores": number;

    /**
     * 分簇使用率：有 P/E 拓扑时由 per-CPU tick 汇总；无区分时为 0
     */
    "perfCpuPercent": number;
    "effCpuPercent": number;

    /**
     * 每个逻辑核使用率（Apple Silicon 核序：先性能核、再能效核）
     */
    "cpuCores": CPUCoreStat[] | null;
    "hostname": string;
    "arch": string;

    /**
     * 内网主 IP
     */
    "ipAddress": string;

    /**
     * 出口公网 IP（缓存探测，可能为空）
     */
    "publicIP": string;

    /**
     * 累计计数：前端差分算速率（对齐 monitor.Overview）
     */
    "netRxBytes": number;
    "netTxBytes": number;
    "diskReadBytes": number;
    "diskWriteBytes": number;
    "diskIOCount": number;

    /**
     * macOS 扩展
     * 如 Mac16,13
     */
    "modelName": string;

    /**
     * 如 macOS
     */
    "productName": string;

    /**
     * 如 15.0
     */
    "productVer": string;
    "disks": DiskInfo[] | null;
    "runtimes": Runtime[] | null;

    /**
     * 系统温度（AppleSMC；不可用时字段为 nil）
     * 综合（CPU/GPU 平均）
     */
    "tempC"?: number | null;

    /**
     * CPU 相关传感器平均
     */
    "cpuTempC"?: number | null;

    /**
     * GPU 相关传感器平均
     */
    "gpuTempC"?: number | null;
}

/**
 * Package 已安装软件。
 */
export interface Package {
    "name": string;
    "version": string;

    /**
     * app / formula / cask
     */
    "source": string;
    "path": string;
}

/**
 * Runtime 已安装的运行时版本。
 */
export interface Runtime {
    "name": string;
    "version": string;
    "path": string;
}

/**
 * StorageApp 按应用汇总的占用。
 */
export interface StorageApp {
    "name": string;
    "bundleId": string;
    "path": string;
    "bundleSize": number;
    "dataSize": number;
    "total": number;
    "parts"?: StorageAppPart[] | null;
}

/**
 * StorageAppPart 应用关联的一块占用。
 */
export interface StorageAppPart {
    "label": string;
    "path": string;
    "size": number;
}

/**
 * StorageFile 大文件条目。
 */
export interface StorageFile {
    "path": string;
    "size": number;

    /**
     * unix 秒
     */
    "modTime": number;
}

/**
 * StorageNode 目录树节点（children 仅一层）。
 */
export interface StorageNode {
    "name": string;
    "path": string;
    "size": number;
    "files": number;
    "dirs": number;
    "isDir": boolean;
    "children"?: StorageNode[] | null;
}

/**
 * StorageStatus 磁盘占用扫描状态。
 * state: idle | running | done | error
 */
export interface StorageStatus {
    "state": string;
    "scannedBytes": number;
    "scannedFiles": number;
    "scannedDirs": number;
    "deniedDirs": number;

    /**
     * 最多保留若干条示例
     */
    "deniedPaths": string[] | null;
    "error"?: string;

    /**
     * unix 秒；0=未开始
     */
    "startedAt": number;

    /**
     * unix 秒
     */
    "finishedAt": number;
    "roots": string[] | null;
    "containerTotal": number;
    "containerUsed": number;
    "containerAvail": number;
}
