// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Preview 文本文件预览结果（展示用 Content 恒为 UTF-8）
 */
export interface Preview {
    "path": string;
    "name": string;

    /**
     * UTF-8 文本（已去掉 BOM 以便编辑/展示）
     */
    "content": string;

    /**
     * 检测标签：UTF-8 / UTF-8 BOM / GBK / GB18030 / UTF-16LE …
     */
    "encoding": string;

    /**
     * LF / CRLF / CR / Mixed / —
     */
    "lineEnding": string;

    /**
     * 非 Linux 标准（非纯 UTF-8 无 BOM + LF）
     */
    "needsNormalize": boolean;

    /**
     * 原始字节数
     */
    "size": number;
}
