// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {monitor} from '../models';
import {groups} from '../models';
import {sshconfig} from '../models';
import {filetext} from '../models';

export function AddHost(arg1:main.AddHostInput):Promise<void>;

export function AssignHost(arg1:string,arg2:string):Promise<void>;

export function AuthStatus():Promise<main.AuthState>;

export function AuthenticateMacUser(arg1:string,arg2:string):Promise<main.AuthState>;

export function AuthenticateWithSystem():Promise<main.AuthState>;

export function CheckLocalPaths(arg1:Array<string>):Promise<Array<main.LocalTextCheck>>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CollectCrons(arg1:string):Promise<Array<monitor.Cron>>;

export function CollectDisks(arg1:string):Promise<Array<monitor.DiskInfo>>;

export function CollectDocker(arg1:string):Promise<monitor.DockerInfo>;

export function CollectJava(arg1:string):Promise<Array<monitor.ProcInfo>>;

export function CollectLargestFiles(arg1:string,arg2:number):Promise<monitor.LargeFilesResult>;

export function CollectNetwork(arg1:string):Promise<monitor.NetworkSnapshot>;

export function CollectOverview(arg1:string):Promise<monitor.Overview>;

export function CollectPackages(arg1:string):Promise<Array<monitor.AptPackage>>;

export function CollectProcesses(arg1:string,arg2:number):Promise<Array<monitor.ProcInfo>>;

export function CollectServices(arg1:string):Promise<Array<monitor.Service>>;

export function CopySSHID(arg1:main.CopyIDInput):Promise<string>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeletePaths(arg1:string,arg2:Array<string>):Promise<string>;

export function DockerAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetCurrentMacUser():Promise<main.MacUserInfo>;

export function GetHomeDir(arg1:string):Promise<string>;

export function KillProcess(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function ListDir(arg1:string,arg2:string):Promise<Array<monitor.FileEntry>>;

export function ListGroupOverview():Promise<Array<main.GroupOverview>>;

export function ListGroups():Promise<Array<groups.Group>>;

export function ListHosts():Promise<Array<sshconfig.HostConfig>>;

export function ListHostsAll():Promise<Array<sshconfig.HostConfig>>;

export function ListOneGroupOverview(arg1:string):Promise<main.GroupOverview>;

export function LogoutMacUser():Promise<main.AuthState>;

export function NormalizeFileToLinux(arg1:string,arg2:string):Promise<filetext.Preview>;

export function OpenTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function ReadFilePreview(arg1:string,arg2:string):Promise<filetext.Preview>;

export function ReadFileText(arg1:string,arg2:string):Promise<string>;

export function RenameGroup(arg1:string,arg2:string):Promise<void>;

export function RenameHost(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TestConnection(arg1:main.AddHostInput):Promise<string>;

export function UpdateHost(arg1:main.UpdateHostInput):Promise<void>;

export function UploadDir(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function UploadFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function UploadPaths(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:string):Promise<void>;

export function UpsertGroup(arg1:groups.Group):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
