// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1) {
  return window['go']['main']['App']['AddHost'](arg1);
}

export function AssignHost(arg1, arg2) {
  return window['go']['main']['App']['AssignHost'](arg1, arg2);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CollectCrons(arg1) {
  return window['go']['main']['App']['CollectCrons'](arg1);
}

export function CollectDisks(arg1) {
  return window['go']['main']['App']['CollectDisks'](arg1);
}

export function CollectDocker(arg1) {
  return window['go']['main']['App']['CollectDocker'](arg1);
}

export function CollectJava(arg1) {
  return window['go']['main']['App']['CollectJava'](arg1);
}

export function CollectOverview(arg1) {
  return window['go']['main']['App']['CollectOverview'](arg1);
}

export function CollectPackages(arg1) {
  return window['go']['main']['App']['CollectPackages'](arg1);
}

export function CollectProcesses(arg1, arg2) {
  return window['go']['main']['App']['CollectProcesses'](arg1, arg2);
}

export function CollectServices(arg1) {
  return window['go']['main']['App']['CollectServices'](arg1);
}

export function CopySSHID(arg1) {
  return window['go']['main']['App']['CopySSHID'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DockerAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['DockerAction'](arg1, arg2, arg3);
}

export function KillProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2, arg3);
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function ListGroupOverview() {
  return window['go']['main']['App']['ListGroupOverview']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function ListHostsAll() {
  return window['go']['main']['App']['ListHostsAll']();
}

export function OpenTerminal(arg1, arg2) {
  return window['go']['main']['App']['OpenTerminal'](arg1, arg2);
}

export function ReadFileText(arg1, arg2) {
  return window['go']['main']['App']['ReadFileText'](arg1, arg2);
}

export function RenameHost(arg1, arg2) {
  return window['go']['main']['App']['RenameHost'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UpsertGroup(arg1) {
  return window['go']['main']['App']['UpsertGroup'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
