// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Item 一条用户自定义巡检：请求定义 + 断言 + 定时规则。
 */
export interface Item {
    "id": string;
    "label": string;
    "method": string;
    "url": string;
    "query": KV[] | null;
    "headers": KV[] | null;
    "body": string;
    "timeoutSec": number;

    /**
     * ExpectStatus 形如 "200"、"2xx"、"200,204"；空表示 2xx–3xx 都算正常。
     */
    "expectStatus": string;
    "mustContain": string[] | null;
    "mustNotContain": string[] | null;
    "scheduleEnabled": boolean;
    "intervalMin": number;

    /**
     * WindowStart/WindowEnd 为 "HH:MM"；两者都空表示全天。End < Start 表示跨零点。
     */
    "windowStart": string;
    "windowEnd": string;
}

/**
 * KV 请求参数或请求头的一行。Enabled=false 的行保留在配置里但不发送。
 */
export interface KV {
    "key": string;
    "value": string;
    "enabled": boolean;
}
