// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    AptPackage,
    CertInfo,
    CertListResult,
    Container,
    ContainerStat,
    Cron,
    DiskInfo,
    DockerInfo,
    EgressInfo,
    FileEntry,
    JavaProcDetail,
    LargeFile,
    LargeFilesResult,
    LogResult,
    NetConnection,
    NetInterface,
    NetworkSnapshot,
    Overview,
    ProcInfo,
    RuntimeCounts,
    RuntimeInfo,
    RuntimeProc,
    Service,
    ServiceDetail
} from "./models.js";
