// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AptPackage {
    "name": string;
    "version": string;

    /**
     * 依赖包数量（apt-cache depends 的 uniq 计数）
     */
    "depends": number;
}

/**
 * CertInfo 单张证书的识别结果（参考 1Panel 证书列表字段）
 */
export interface CertInfo {
    /**
     * 证书文件名
     */
    "name": string;

    /**
     * CN + SAN 域名（去重）
     */
    "domains": string[] | null;

    /**
     * 颁发者（CN 优先，回退 O）
     */
    "issuer": string;

    /**
     * 到期时间（Unix 秒）
     */
    "notAfter": number;

    /**
     * 剩余天数（负数 = 已过期）
     */
    "daysLeft": number;

    /**
     * 颁发者 == 使用者 视为自签名
     */
    "selfSigned": boolean;

    /**
     * 同名 .key 是否存在
     */
    "hasKey": boolean;

    /**
     * 匹配到的私钥文件名
     */
    "keyName": string;

    /**
     * 证书文件大小（字节）
     */
    "size": number;

    /**
     * 文件修改时间（Unix 秒）
     */
    "mtime": number;
}

/**
 * CertListResult /etc/nginx/cert 的整体识别结果
 */
export interface CertListResult {
    /**
     * 目录是否存在
     */
    "installed": boolean;

    /**
     * 远程缺少 openssl，无法解析证书内容
     */
    "noOpenssl": boolean;
    "certs": CertInfo[] | null;
}

export interface Container {
    "id": string;
    "name": string;
    "image": string;
    "status": string;
    "state": string;
    "ports": string;
}

export interface ContainerStat {
    "name": string;
    "cpuPercent": number;
    "memUsage": number;
    "memLimit": number;
    "memPercent": number;
    "netIn": number;
    "netOut": number;
    "blockIn": number;
    "blockOut": number;
}

export interface Cron {
    "user": string;
    "line": string;

    /**
     * user / etc-cron.d / etc-crontab
     */
    "source": string;
}

export interface DiskInfo {
    "filesystem": string;
    "fsType": string;
    "mount": string;
    "total": number;
    "used": number;
    "avail": number;
    "percent": number;
}

export interface DockerInfo {
    /**
     * 目标机是否有 docker
     */
    "available": boolean;
    "containers": Container[] | null;
    "stats": ContainerStat[] | null;
}

/**
 * EgressInfo 出口公网信息（来自 myip.ipip.net）
 */
export interface EgressInfo {
    "ip": string;
    "location": string;
    "raw": string;
}

/**
 * FileEntry 目录中一个条目
 */
export interface FileEntry {
    "name": string;

    /**
     * 绝对路径
     */
    "path": string;
    "isDir": boolean;

    /**
     * 字节，目录为 0
     */
    "size": number;

    /**
     * 形如 "drwxr-xr-x"
     */
    "mode": string;

    /**
     * 形如 "2025-01-01 12:34"
     */
    "modTime": string;

    /**
     * 形如 "root"
     */
    "owner": string;
    "group": string;
}

/**
 * JavaProcDetail 单个运行时进程的补充详情（悬浮卡片按需查询）
 */
export interface JavaProcDetail {
    "pid": number;

    /**
     * /proc/<pid>/cwd
     */
    "workDir": string;

    /**
     * /proc/<pid>/exe（可执行文件真实路径）
     */
    "exePath": string;

    /**
     * /proc/<pid>/io 累计读（无权限时为 0）
     */
    "readBytes": number;

    /**
     * 累计写
     */
    "writeBytes": number;
}

/**
 * LargeFile 磁盘上体积较大的普通文件
 */
export interface LargeFile {
    /**
     * 文件名
     */
    "name": string;

    /**
     * 所在目录
     */
    "dir": string;

    /**
     * 完整路径
     */
    "path": string;

    /**
     * 字节
     */
    "size": number;
}

/**
 * LargeFilesResult 扫描结果
 */
export interface LargeFilesResult {
    "files": LargeFile[] | null;

    /**
     * 超时/截断
     */
    "incomplete": boolean;
    "message"?: string;
    "elapsedMs": number;
}

/**
 * LogResult 日志采集结果（末尾 N 行）
 */
export interface LogResult {
    /**
     * 日志文本
     */
    "content": string;

    /**
     * 数据来源（如 /var/log/syslog；空表示未找到）
     */
    "source": string;
}

/**
 * NetConnection 一条 TCP 连接
 */
export interface NetConnection {
    "proto": string;
    "state": string;
    "localAddr": string;
    "remoteAddr": string;
    "recvQ": number;
    "sendQ": number;
    "pid": number;
    "process": string;
    "slow": boolean;
    "slowReason"?: string;
    "rttMs"?: number;
}

/**
 * NetInterface 网卡信息
 */
export interface NetInterface {
    "name": string;

    /**
     * UP / DOWN
     */
    "state": string;
    "mtu": number;
    "mac": string;
    "ipv4": string[] | null;

    /**
     * physical | docker | virtual | loopback | other
     */
    "kind": string;
    "rxBytes": number;
    "txBytes": number;
    "rxPackets": number;
    "txPackets": number;
}

/**
 * NetworkSnapshot 目标主机网络全景
 */
export interface NetworkSnapshot {
    "interfaces": NetInterface[] | null;

    /**
     * 汇总 IP：内网 / 外网 / Docker 网桥
     */
    "privateIPs": string[] | null;
    "publicIPs": string[] | null;
    "dockerIPs": string[] | null;

    /**
     * 出口公网 IP（访问 myip.ipip.net 解析，可能为空）
     */
    "egressPublicIP": string;

    /**
     * 出口公网归属地（myip.ipip.net「来自于」字段，可能为空）
     */
    "egressPublicLoc": string;

    /**
     * 默认路由网关
     */
    "defaultGateway": string;

    /**
     * TCP 连接（含进程）
     */
    "connections": NetConnection[] | null;

    /**
     * 疑似网络响应卡顿的连接/进程（高亮用）
     */
    "slowConnections": NetConnection[] | null;

    /**
     * 统计
     */
    "connTotal": number;
    "connEstablished": number;
    "connListen": number;
    "connTimeWait": number;
}

/**
 * Overview 顶层系统指标
 */
export interface Overview {
    /**
     * 总体 CPU 使用率
     */
    "cpuPercent": number;

    /**
     * 内存使用率
     */
    "memPercent": number;

    /**
     * 内存总量 bytes
     */
    "memTotal": number;

    /**
     * 已用内存
     */
    "memUsed": number;

    /**
     * swap 使用率
     */
    "swapPercent": number;
    "swapTotal": number;
    "swapUsed": number;

    /**
     * 1 分钟负载
     */
    "load1": number;
    "load5": number;
    "load15": number;

    /**
     * 启动至今的秒数
     */
    "uptime": number;
    "kernel": string;
    "osRelease": string;
    "cpuCount": number;
    "cpuModel": string;

    /**
     * 1Panel 风格概览扩展
     * 主机名
     */
    "hostname": string;

    /**
     * 系统架构 uname -m
     */
    "arch": string;

    /**
     * 主网卡 IP（尽力获取）
     */
    "ipAddress": string;

    /**
     * 累计接收字节（默认路由网卡，如 eth0；探测失败则全网卡合计不含 lo）
     */
    "netRxBytes": number;

    /**
     * 累计发送字节（同上）
     */
    "netTxBytes": number;

    /**
     * 磁盘 IO 累计值（仅物理块设备合计，不含分区/虚拟设备；前端差分算速率）
     * 累计读字节（sectors_read × 512）
     */
    "diskReadBytes": number;

    /**
     * 累计写字节
     */
    "diskWriteBytes": number;

    /**
     * 累计读写操作次数（reads + writes completed）
     */
    "diskIOCount": number;
}

export interface ProcInfo {
    "pid": number;
    "ppid": number;
    "user": string;
    "cpu": number;
    "mem": number;

    /**
     * 物理内存 bytes
     */
    "rss": number;

    /**
     * 启动至今秒数
     */
    "elapsed": number;
    "cmd": string;
}

/**
 * RuntimeCounts 各运行时正在运行的进程数（进程页标签徽标）
 */
export interface RuntimeCounts {
    "java": number;
    "go": number;
    "node": number;
    "bun": number;
    "python": number;

    /**
     * 容器数（含已停止；无 docker / 无权限时为 0）
     */
    "docker": number;
}

/**
 * RuntimeInfo 常用运行环境的识别结果（未安装时 Version/Path 为空）
 */
export interface RuntimeInfo {
    /**
     * java / go / python / node / bun
     */
    "name": string;

    /**
     * 提取的版本号，如 17.0.2
     */
    "version": string;

    /**
     * 可执行文件绝对路径
     */
    "path": string;

    /**
     * 版本命令原始输出首行（悬浮查看）
     */
    "detail": string;
}

/**
 * RuntimeProc 运行时进程（java/go/node/bun/python）的列表信息（进程页各运行时视图主列表）
 */
export interface RuntimeProc {
    "pid": number;
    "user": string;
    "cpu": number;

    /**
     * 百分比
     */
    "mem": number;

    /**
     * bytes
     */
    "rss": number;
    "elapsed": number;

    /**
     * 完整命令行
     */
    "args": string;

    /**
     * 入口：java=jar 路径；node/bun/python=脚本；go=可执行文件路径
     */
    "entry": string;

    /**
     * 仅 java：-Xms 初始堆 bytes（未显式设置为 0）
     */
    "xms": number;

    /**
     * 仅 java：-Xmx 最大堆 bytes
     */
    "xmx": number;
    "ports": string[] | null;

    /**
     * systemd / docker / process
     */
    "deploy": string;

    /**
     * systemd 服务名（含 .service，systemd 部署时）
     */
    "service": string;

    /**
     * docker 容器名（docker 部署时）
     */
    "container": string;

    /**
     * docker 镜像（docker 部署时）
     */
    "image": string;
}

export interface Service {
    "name": string;
    "load": string;

    /**
     * active / failed / inactive
     */
    "active": string;
    "sub": string;
    "description": string;
}

/**
 * ServiceDetail 单个服务的详细信息（systemctl show 按需查询，供悬浮卡片展示）
 */
export interface ServiceDetail {
    "id": string;
    "description": string;
    "loadState": string;
    "activeState": string;
    "subState": string;
    "mainPid": string;
    "execStart": string;
    "fragmentPath": string;
    "activeEnterTimestamp": string;
    "memoryCurrent": string;
    "cpuTimeNsec": string;
    "restart": string;
    "user": string;
}
